/* ─────────────────────────────────────────────────────────────
   삐릿빠릿 — 고교 필수 영단어 사전
   사진에서 뽑아낸 단어에 한글 뜻을 자동으로 붙이기 위한 데이터.
   API 키도, 서버도 필요 없다. 브라우저가 이 파일만 읽으면 된다.

   여기에 없는 단어는 학생이 직접 뜻을 적어 넣는다.
   자주 나오는데 빠진 단어가 보이면 아래 목록에 한 줄 추가하면 된다.
   ───────────────────────────────────────────────────────────── */
window.VOCAB_DICT = {
"abandon":"버리다, 포기하다",
"ability":"능력, 재능",
"abroad":"해외로, 해외에",
"absence":"결석, 부재",
"absolute":"절대적인, 완전한",
"absorb":"흡수하다, 몰두시키다",
"abstract":"추상적인",
"abundant":"풍부한",
"abuse":"남용하다, 학대하다",
"academic":"학문의, 학업의",
"accept":"받아들이다, 수락하다",
"access":"접근, 이용 권한",
"accident":"사고, 우연",
"accompany":"동행하다, 동반하다",
"accomplish":"성취하다, 해내다",
"account":"계좌, 설명, 계정",
"accurate":"정확한",
"accuse":"고발하다, 비난하다",
"achieve":"달성하다, 이루다",
"acknowledge":"인정하다, 승인하다",
"acquire":"습득하다, 얻다",
"active":"활동적인, 적극적인",
"actual":"실제의",
"adapt":"적응하다, 각색하다",
"add":"더하다, 추가하다",
"addition":"추가, 덧셈",
"address":"주소; 연설하다, 다루다",
"adequate":"충분한, 적절한",
"adjust":"조절하다, 적응하다",
"admire":"존경하다, 감탄하다",
"admit":"인정하다, 입장을 허락하다",
"adolescent":"청소년",
"adopt":"채택하다, 입양하다",
"advance":"전진하다; 발전",
"advantage":"이점, 유리함",
"adventure":"모험",
"advertise":"광고하다",
"advice":"조언, 충고",
"affect":"영향을 미치다",
"afford":"~할 여유가 있다",
"afraid":"두려워하는",
"agency":"대행사, 기관",
"agenda":"의제, 안건",
"aggressive":"공격적인, 적극적인",
"agree":"동의하다",
"agriculture":"농업",
"aid":"도움; 돕다",
"aim":"목표; 겨냥하다",
"alarm":"경보; 놀라게 하다",
"alert":"경계하는; 경보",
"alien":"외계인; 낯선",
"alike":"비슷한",
"alive":"살아 있는",
"allow":"허락하다",
"ally":"동맹국, 협력자",
"alter":"바꾸다, 변경하다",
"alternative":"대안; 대체의",
"amaze":"놀라게 하다",
"ambition":"야망, 포부",
"amount":"양, 총액",
"amuse":"즐겁게 하다",
"analyze":"분석하다",
"ancestor":"조상",
"ancient":"고대의",
"anger":"분노",
"angle":"각도, 관점",
"announce":"발표하다, 알리다",
"annoy":"짜증나게 하다",
"annual":"매년의, 연례의",
"anxiety":"불안, 걱정",
"apart":"떨어져서, 따로",
"apologize":"사과하다",
"apparent":"명백한, 겉보기의",
"appeal":"호소하다; 매력",
"appear":"나타나다, ~처럼 보이다",
"appetite":"식욕, 욕구",
"apply":"지원하다, 적용하다",
"appoint":"임명하다, 정하다",
"appreciate":"감사하다, 진가를 알다",
"approach":"접근하다; 접근법",
"appropriate":"적절한",
"approve":"승인하다, 찬성하다",
"approximate":"대략의",
"architecture":"건축, 건축학",
"argue":"주장하다, 논쟁하다",
"arise":"발생하다, 생기다",
"arrange":"정리하다, 준비하다",
"arrest":"체포하다",
"arrive":"도착하다",
"artificial":"인공적인",
"ashamed":"부끄러워하는",
"aspect":"측면, 양상",
"assemble":"조립하다, 모으다",
"assert":"주장하다",
"assess":"평가하다",
"asset":"자산",
"assign":"할당하다, 배정하다",
"assist":"돕다",
"associate":"연관 짓다; 동료",
"assume":"가정하다, 추정하다",
"assure":"확신시키다, 보장하다",
"astonish":"깜짝 놀라게 하다",
"athlete":"운동선수",
"atmosphere":"대기, 분위기",
"attach":"붙이다, 첨부하다",
"attack":"공격하다; 공격",
"attempt":"시도하다; 시도",
"attend":"참석하다, 다니다",
"attention":"주의, 관심",
"attitude":"태도, 자세",
"attract":"끌어당기다, 매혹하다",
"attribute":"~의 탓으로 돌리다; 속성",
"audience":"청중, 관객",
"authority":"권위, 당국",
"available":"이용 가능한",
"average":"평균; 평균의",
"avoid":"피하다",
"awake":"깨어 있는",
"aware":"알고 있는, 인식하는",
"awful":"끔찍한",
"awkward":"어색한, 곤란한",
"background":"배경",
"balance":"균형; 균형을 잡다",
"ban":"금지하다; 금지",
"bare":"벌거벗은, 텅 빈",
"bargain":"흥정하다; 싼 물건",
"barrier":"장벽, 장애물",
"basic":"기본적인",
"battle":"전투; 싸우다",
"bear":"참다, 낳다; 곰",
"beg":"간청하다, 구걸하다",
"behave":"행동하다",
"belief":"믿음, 신념",
"belong":"속하다",
"beneath":"~아래에",
"benefit":"이익; 이익을 주다",
"betray":"배신하다",
"beyond":"~너머에, ~을 넘어서",
"bias":"편견, 선입견",
"bind":"묶다, 결속시키다",
"biology":"생물학",
"bitter":"쓴, 씁쓸한",
"blame":"비난하다; 책임",
"blank":"빈; 빈칸",
"blend":"섞다, 혼합하다",
"bless":"축복하다",
"blind":"눈먼, 맹목적인",
"bloom":"꽃이 피다; 꽃",
"boast":"자랑하다",
"bold":"대담한, 굵은",
"bond":"유대, 결속, 채권",
"boost":"북돋우다, 신장시키다",
"border":"국경, 경계",
"bother":"귀찮게 하다, 신경 쓰다",
"bounce":"튀다, 반등하다",
"brave":"용감한",
"breed":"기르다, 번식하다; 품종",
"brief":"간단한, 짧은",
"brilliant":"뛰어난, 눈부신",
"broad":"넓은",
"broadcast":"방송하다; 방송",
"budget":"예산",
"burden":"부담, 짐",
"burst":"터지다, 파열하다",
"bury":"묻다, 매장하다",
"calculate":"계산하다",
"campaign":"캠페인, 운동",
"cancel":"취소하다",
"candidate":"후보자, 지원자",
"capable":"~할 수 있는, 유능한",
"capacity":"수용력, 능력",
"capital":"수도, 자본; 대문자의",
"capture":"포획하다, 담아내다",
"carbon":"탄소",
"career":"경력, 직업",
"carve":"조각하다, 새기다",
"casual":"평상시의, 무심한",
"cause":"원인; 야기하다",
"caution":"주의, 경고",
"cease":"멈추다, 중단하다",
"celebrate":"축하하다, 기념하다",
"cell":"세포, 감방",
"census":"인구 조사",
"century":"세기, 100년",
"ceremony":"의식, 예식",
"certain":"확실한, 어떤",
"challenge":"도전; 이의를 제기하다",
"chamber":"방, 회의실",
"chaos":"혼돈, 혼란",
"character":"성격, 등장인물, 문자",
"charge":"청구하다, 충전하다; 요금",
"charity":"자선, 자선 단체",
"chase":"쫓다, 추격하다",
"cheat":"속이다, 부정행위를 하다",
"chemical":"화학의; 화학 물질",
"chief":"주요한; 우두머리",
"circumstance":"상황, 환경",
"cite":"인용하다",
"citizen":"시민",
"civil":"시민의, 민간의",
"claim":"주장하다; 주장",
"clarify":"명확히 하다",
"classify":"분류하다",
"client":"고객, 의뢰인",
"climate":"기후",
"cling":"달라붙다, 매달리다",
"clue":"단서, 실마리",
"coast":"해안",
"code":"암호, 규범, 코드",
"cognitive":"인지의",
"coincidence":"우연의 일치",
"collapse":"붕괴하다; 붕괴",
"colleague":"동료",
"collect":"모으다, 수집하다",
"colony":"식민지, 군집",
"combine":"결합하다",
"comfort":"위로하다; 편안함",
"command":"명령하다; 명령",
"comment":"논평하다; 논평",
"commerce":"상업, 무역",
"commit":"저지르다, 헌신하다",
"committee":"위원회",
"common":"흔한, 공통의",
"communicate":"의사소통하다",
"community":"공동체, 지역 사회",
"compare":"비교하다",
"compete":"경쟁하다",
"complain":"불평하다",
"complete":"완전한; 완료하다",
"complex":"복잡한; 복합 건물",
"component":"구성 요소, 부품",
"compose":"구성하다, 작곡하다",
"comprehend":"이해하다",
"compromise":"타협하다; 타협",
"conceal":"숨기다",
"concentrate":"집중하다",
"concept":"개념",
"concern":"걱정; 관련되다",
"conclude":"결론짓다, 끝내다",
"concrete":"구체적인; 콘크리트",
"condition":"상태, 조건",
"conduct":"수행하다; 행동",
"confess":"고백하다, 자백하다",
"confident":"자신 있는, 확신하는",
"confine":"제한하다, 가두다",
"confirm":"확인하다, 확정하다",
"conflict":"갈등, 충돌",
"confront":"직면하다, 맞서다",
"confuse":"혼동시키다, 혼란스럽게 하다",
"congratulate":"축하하다",
"connect":"연결하다",
"conquer":"정복하다",
"conscious":"의식하는, 의식이 있는",
"consent":"동의; 동의하다",
"consequence":"결과, 영향",
"conserve":"보존하다, 아끼다",
"consider":"고려하다, ~로 여기다",
"consist":"구성되다",
"constant":"끊임없는, 일정한",
"constitute":"구성하다, ~이 되다",
"construct":"건설하다, 구성하다",
"consult":"상담하다, 참고하다",
"consume":"소비하다, 소모하다",
"contact":"연락하다; 접촉",
"contain":"포함하다, 담고 있다",
"contemporary":"현대의, 동시대의",
"content":"내용; 만족하는",
"context":"맥락, 문맥",
"continent":"대륙",
"continue":"계속하다",
"contract":"계약; 수축하다",
"contrast":"대조; 대조하다",
"contribute":"기여하다, 기부하다",
"control":"통제하다; 통제",
"convenient":"편리한",
"conventional":"전통적인, 관습적인",
"conversation":"대화",
"convert":"전환하다, 개종시키다",
"convey":"전달하다, 나르다",
"convince":"확신시키다, 설득하다",
"cooperate":"협력하다",
"cope":"대처하다",
"core":"핵심; 핵심의",
"corporate":"기업의, 법인의",
"correct":"올바른; 고치다",
"correspond":"일치하다, 서신을 주고받다",
"corrupt":"부패한; 타락시키다",
"costume":"의상, 복장",
"council":"의회, 협의회",
"counsel":"조언하다; 조언",
"count":"세다, 중요하다",
"courage":"용기",
"court":"법정, 코트",
"cover":"덮다, 다루다; 덮개",
"crash":"충돌하다; 충돌",
"create":"창조하다, 만들다",
"creature":"생물, 창조물",
"credit":"신용, 학점, 공로",
"crew":"승무원, 팀",
"crime":"범죄",
"crisis":"위기",
"criterion":"기준",
"critical":"비판적인, 중요한, 위독한",
"criticize":"비판하다",
"crop":"작물, 수확량",
"crowd":"군중; 붐비다",
"crucial":"결정적인, 중대한",
"cruel":"잔인한",
"cue":"신호, 단서",
"cultivate":"경작하다, 기르다",
"curious":"호기심 많은, 기이한",
"currency":"통화, 화폐",
"current":"현재의; 흐름, 해류",
"curriculum":"교육 과정",
"custom":"관습, 풍습"
};

Object.assign(window.VOCAB_DICT, {
"damage":"손상; 손상시키다",
"dare":"감히 ~하다",
"deal":"거래; 다루다",
"debate":"토론; 토론하다",
"debt":"빚, 부채",
"decade":"10년",
"decay":"부패하다, 쇠퇴하다",
"deceive":"속이다",
"declare":"선언하다, 신고하다",
"decline":"감소하다, 거절하다; 감소",
"decorate":"장식하다",
"decrease":"감소하다; 감소",
"dedicate":"헌신하다, 바치다",
"defeat":"패배시키다; 패배",
"defend":"방어하다, 변호하다",
"define":"정의하다",
"definite":"명확한, 확실한",
"degree":"정도, 학위, 도",
"delay":"지연시키다; 지연",
"deliberate":"고의의, 신중한",
"delicate":"섬세한, 연약한",
"deliver":"배달하다, 전달하다",
"demand":"요구하다; 수요",
"democracy":"민주주의",
"demonstrate":"입증하다, 시위하다",
"deny":"부인하다, 거부하다",
"depart":"출발하다, 떠나다",
"depend":"의존하다, ~에 달려 있다",
"depict":"묘사하다",
"deposit":"예금하다; 보증금, 침전물",
"depress":"우울하게 하다, 침체시키다",
"deprive":"박탈하다, 빼앗다",
"derive":"유래하다, 끌어내다",
"descend":"내려가다, 하강하다",
"describe":"묘사하다, 설명하다",
"desert":"사막; 버리다",
"deserve":"~할 만하다, 자격이 있다",
"design":"설계하다; 디자인",
"desire":"욕망; 바라다",
"despair":"절망",
"desperate":"절망적인, 필사적인",
"despite":"~에도 불구하고",
"destination":"목적지",
"destroy":"파괴하다",
"detail":"세부 사항",
"detect":"탐지하다, 발견하다",
"determine":"결정하다, 알아내다",
"develop":"발전시키다, 개발하다",
"device":"장치, 기기",
"devote":"바치다, 헌신하다",
"diagnose":"진단하다",
"differ":"다르다",
"digest":"소화하다, 이해하다",
"dignity":"존엄성, 품위",
"diligent":"부지런한",
"dimension":"차원, 치수",
"diminish":"줄어들다, 감소시키다",
"direct":"직접적인; 지시하다, 감독하다",
"disabled":"장애가 있는",
"disappear":"사라지다",
"disappoint":"실망시키다",
"disaster":"재난, 재해",
"discipline":"규율, 훈련, 학문 분야",
"discourage":"낙담시키다, 단념시키다",
"discover":"발견하다",
"discriminate":"차별하다, 구별하다",
"discuss":"논의하다",
"disease":"질병",
"disguise":"변장하다; 위장",
"disgust":"혐오감; 역겹게 하다",
"dismiss":"묵살하다, 해고하다",
"display":"전시하다; 전시",
"dispose":"처리하다, 배치하다",
"dispute":"분쟁; 반박하다",
"distance":"거리",
"distinct":"뚜렷한, 별개의",
"distinguish":"구별하다",
"distribute":"분배하다, 유통시키다",
"district":"지역, 지구",
"disturb":"방해하다, 어지럽히다",
"diverse":"다양한",
"divide":"나누다, 분열시키다",
"divorce":"이혼; 이혼하다",
"document":"문서; 기록하다",
"domain":"영역, 분야",
"domestic":"국내의, 가정의",
"dominate":"지배하다, 우세하다",
"donate":"기부하다",
"doubt":"의심; 의심하다",
"drag":"끌다, 질질 끌다",
"drain":"배수하다, 소모시키다",
"dramatic":"극적인",
"drought":"가뭄",
"due":"~때문인, 만기의, 예정된",
"dull":"지루한, 둔한",
"duty":"의무, 임무, 세금",
"dye":"염색하다; 염료",
"eager":"열망하는, 간절한",
"earn":"벌다, 얻다",
"ease":"쉬움, 편안함; 완화하다",
"echo":"메아리; 반향하다",
"ecology":"생태학, 생태",
"economy":"경제, 절약",
"edge":"가장자리, 우위",
"edit":"편집하다, 수정하다",
"educate":"교육하다",
"effect":"효과, 영향",
"efficient":"효율적인",
"effort":"노력",
"elaborate":"정교한; 자세히 설명하다",
"elect":"선출하다",
"electric":"전기의",
"element":"요소, 원소",
"eliminate":"제거하다, 없애다",
"embarrass":"당황하게 하다",
"embrace":"포옹하다, 받아들이다",
"emerge":"나타나다, 부상하다",
"emergency":"비상사태",
"emit":"내뿜다, 방출하다",
"emotion":"감정",
"emphasize":"강조하다",
"empire":"제국",
"employ":"고용하다, 사용하다",
"empty":"비어 있는; 비우다",
"enable":"가능하게 하다",
"encounter":"마주치다; 만남",
"encourage":"격려하다, 장려하다",
"endure":"견디다, 지속되다",
"enemy":"적",
"energy":"에너지, 활력",
"enforce":"시행하다, 집행하다",
"engage":"관여하다, 참여시키다",
"enhance":"향상시키다, 높이다",
"enormous":"거대한, 막대한",
"ensure":"보장하다, 확실히 하다",
"enterprise":"기업, 사업",
"entertain":"즐겁게 하다, 대접하다",
"enthusiasm":"열정, 열의",
"entire":"전체의",
"entitle":"자격을 주다, 제목을 붙이다",
"environment":"환경",
"envy":"부러워하다; 부러움",
"equal":"동등한; 같다",
"equipment":"장비",
"equivalent":"동등한 것; 상응하는",
"era":"시대",
"erase":"지우다",
"error":"오류, 실수",
"escape":"탈출하다; 탈출",
"essential":"필수적인, 본질적인",
"establish":"설립하다, 확립하다",
"estate":"부동산, 재산",
"estimate":"추정하다; 추정치",
"ethic":"윤리",
"evaluate":"평가하다",
"eventually":"결국, 마침내",
"evidence":"증거",
"evolve":"진화하다, 발전하다",
"exact":"정확한",
"exaggerate":"과장하다",
"examine":"조사하다, 검사하다",
"exceed":"초과하다, 넘어서다",
"excellent":"훌륭한",
"except":"~을 제외하고",
"exchange":"교환하다; 교환",
"exclude":"제외하다, 배제하다",
"excuse":"변명; 용서하다",
"execute":"실행하다, 처형하다",
"exhaust":"고갈시키다, 지치게 하다",
"exhibit":"전시하다; 전시회",
"exist":"존재하다",
"expand":"확장하다, 팽창하다",
"expect":"기대하다, 예상하다",
"expense":"비용, 지출",
"experience":"경험; 경험하다",
"experiment":"실험",
"expert":"전문가",
"explain":"설명하다",
"explode":"폭발하다",
"exploit":"착취하다, 활용하다",
"explore":"탐험하다, 탐구하다",
"export":"수출하다; 수출",
"expose":"노출시키다, 폭로하다",
"express":"표현하다; 급행의",
"extend":"연장하다, 확장하다",
"extent":"정도, 범위",
"external":"외부의",
"extinct":"멸종한",
"extract":"추출하다; 발췌",
"extreme":"극단적인; 극단",
"facility":"시설, 설비",
"factor":"요인, 요소",
"faculty":"능력, 교수진",
"fade":"희미해지다, 바래다",
"fail":"실패하다",
"faint":"희미한; 기절하다",
"fair":"공정한; 박람회",
"faith":"믿음, 신뢰",
"false":"거짓의, 잘못된",
"fame":"명성",
"familiar":"익숙한, 친숙한",
"famine":"기근",
"fancy":"화려한; 상상하다",
"fare":"요금",
"fascinate":"매혹하다",
"fashion":"유행, 방식",
"fatal":"치명적인",
"fate":"운명",
"fault":"결점, 잘못",
"favor":"호의; 선호하다",
"feature":"특징; 특징으로 삼다",
"fee":"수수료, 요금",
"feed":"먹이다, 먹이를 주다",
"fellow":"동료; 동료의",
"female":"여성의; 여성",
"fertile":"비옥한, 가임의",
"fetch":"가져오다",
"fever":"열, 열병",
"fiber":"섬유",
"fiction":"소설, 허구",
"fierce":"사나운, 격렬한",
"figure":"수치, 인물, 형태; 생각해내다",
"file":"파일; 정리하다, 제출하다",
"finance":"재정, 금융",
"firm":"회사; 단단한, 확고한",
"flame":"불꽃",
"flat":"평평한; 아파트",
"flavor":"맛, 풍미",
"flee":"달아나다, 도망치다",
"flexible":"유연한, 융통성 있는",
"float":"뜨다, 떠다니다",
"flood":"홍수; 범람하다",
"flow":"흐르다; 흐름",
"fluent":"유창한",
"focus":"집중하다; 초점",
"fold":"접다",
"forbid":"금지하다",
"force":"힘; 강요하다",
"forecast":"예보하다; 예보",
"forgive":"용서하다",
"formal":"공식적인, 격식을 차린",
"former":"이전의, 전자의",
"fortune":"행운, 재산",
"foster":"기르다, 촉진하다",
"foundation":"기초, 재단",
"fragile":"부서지기 쉬운, 연약한",
"frame":"틀, 액자; 구성하다",
"frequent":"빈번한",
"friction":"마찰",
"frighten":"겁먹게 하다",
"frontier":"국경, 최전선",
"frustrate":"좌절시키다",
"fuel":"연료; 부추기다",
"fulfill":"이행하다, 충족시키다",
"function":"기능; 작동하다",
"fund":"기금; 자금을 대다",
"fundamental":"근본적인, 기본적인",
"funeral":"장례식",
"furniture":"가구",
"further":"더 나아가; 더 이상의",
"gain":"얻다; 이득",
"gap":"간격, 격차",
"garbage":"쓰레기",
"gather":"모으다, 모이다",
"gaze":"응시하다; 응시",
"gender":"성별",
"gene":"유전자",
"general":"일반적인; 장군",
"generate":"발생시키다, 창출하다",
"generous":"관대한, 후한",
"genius":"천재",
"genuine":"진짜의, 진심 어린",
"gesture":"몸짓, 제스처",
"glance":"흘긋 보다; 흘긋 봄",
"glimpse":"언뜻 봄",
"globe":"지구, 구체",
"glory":"영광",
"govern":"통치하다, 지배하다",
"grab":"움켜쥐다, 붙잡다",
"grace":"우아함, 은혜",
"gradual":"점진적인",
"grain":"곡물, 알갱이",
"grant":"승인하다, 수여하다; 보조금",
"grasp":"움켜쥐다, 파악하다",
"grateful":"감사하는",
"gravity":"중력, 중대함",
"greed":"탐욕",
"greet":"인사하다, 맞이하다",
"grief":"슬픔, 비탄",
"grind":"갈다, 빻다",
"guarantee":"보장하다; 보증",
"guard":"지키다; 경비원",
"guilty":"유죄의, 죄책감을 느끼는",
"habit":"습관",
"halt":"멈추다; 정지",
"handle":"다루다, 처리하다; 손잡이",
"harbor":"항구; 품다",
"hardly":"거의 ~않다",
"harm":"해; 해치다",
"harsh":"가혹한, 거친",
"harvest":"수확; 수확하다",
"haste":"서두름",
"hatred":"증오",
"haunt":"출몰하다, 계속 떠오르다",
"hazard":"위험, 위험 요소",
"heal":"치유하다, 낫다",
"heap":"더미",
"hedge":"울타리",
"heritage":"유산",
"hesitate":"주저하다, 망설이다",
"hide":"숨기다, 숨다",
"highlight":"강조하다; 하이라이트",
"hire":"고용하다, 빌리다",
"historic":"역사적인",
"hollow":"속이 빈",
"honest":"정직한",
"honor":"명예; 존경하다",
"horizon":"수평선, 지평선",
"horror":"공포",
"hostile":"적대적인",
"household":"가정, 가구",
"humble":"겸손한, 소박한",
"humid":"습한",
"hunger":"굶주림, 배고픔",
"hunt":"사냥하다; 사냥",
"hurry":"서두르다",
"hypothesis":"가설"
});

Object.assign(window.VOCAB_DICT, {
"ideal":"이상적인; 이상",
"identical":"동일한",
"identify":"확인하다, 알아보다",
"identity":"정체성, 신원",
"ignore":"무시하다",
"illegal":"불법의",
"illusion":"착각, 환상",
"illustrate":"설명하다, 삽화를 넣다",
"imaginary":"상상의, 가상의",
"imitate":"모방하다",
"immediate":"즉각적인",
"immigrant":"이민자",
"immune":"면역의, 면제된",
"impact":"영향, 충격",
"implement":"시행하다; 도구",
"imply":"암시하다, 함축하다",
"import":"수입하다; 수입",
"impose":"부과하다, 강요하다",
"impress":"깊은 인상을 주다",
"improve":"개선하다, 향상되다",
"impulse":"충동, 자극",
"incident":"사건",
"include":"포함하다",
"income":"소득, 수입",
"increase":"증가하다; 증가",
"indeed":"실제로, 정말로",
"independent":"독립적인",
"indicate":"나타내다, 가리키다",
"individual":"개인; 개별의",
"industry":"산업, 업계",
"inevitable":"불가피한",
"infant":"유아",
"infect":"감염시키다",
"infer":"추론하다",
"inferior":"열등한, 하위의",
"inflation":"물가 상승, 인플레이션",
"influence":"영향; 영향을 미치다",
"inform":"알리다, 통지하다",
"ingredient":"재료, 성분",
"inhabit":"거주하다, 서식하다",
"inherit":"물려받다, 상속하다",
"initial":"처음의; 이니셜",
"initiate":"시작하다, 착수하다",
"injure":"부상을 입히다",
"innocent":"무죄의, 순진한",
"innovate":"혁신하다",
"input":"입력; 투입하다",
"inquire":"묻다, 문의하다",
"insect":"곤충",
"insert":"삽입하다",
"insight":"통찰력",
"insist":"주장하다, 고집하다",
"inspect":"점검하다, 검사하다",
"inspire":"영감을 주다, 고무하다",
"install":"설치하다",
"instance":"사례, 경우",
"instant":"즉각적인; 순간",
"instead":"대신에",
"instinct":"본능",
"institute":"기관; 도입하다",
"instruct":"지시하다, 가르치다",
"instrument":"기구, 악기",
"insult":"모욕하다; 모욕",
"insurance":"보험",
"intake":"섭취(량)",
"integrate":"통합하다",
"intellectual":"지적인; 지식인",
"intend":"의도하다, ~할 작정이다",
"intense":"강렬한, 극심한",
"interact":"상호 작용하다",
"interfere":"방해하다, 간섭하다",
"internal":"내부의",
"interpret":"해석하다, 통역하다",
"interrupt":"방해하다, 중단시키다",
"interval":"간격, 사이",
"intervene":"개입하다, 중재하다",
"intimate":"친밀한",
"introduce":"소개하다, 도입하다",
"invade":"침입하다, 침략하다",
"invent":"발명하다",
"invest":"투자하다",
"investigate":"조사하다, 수사하다",
"invisible":"보이지 않는",
"invite":"초대하다",
"involve":"관련시키다, 수반하다",
"iron":"철; 다림질하다",
"irrigation":"관개",
"isolate":"고립시키다, 분리하다",
"issue":"문제, 발행물; 발행하다",
"item":"항목, 품목",
"jealous":"질투하는",
"journal":"학술지, 일기",
"journey":"여행, 여정",
"judge":"판단하다; 판사",
"justice":"정의, 사법",
"justify":"정당화하다",
"keen":"열망하는, 예리한",
"knowledge":"지식",
"labor":"노동; 노동하다",
"lack":"부족; 부족하다",
"landscape":"풍경, 경관",
"latter":"후자의, 후반의",
"launch":"출시하다, 발사하다",
"layer":"층, 겹",
"lean":"기대다, 기울다; 마른",
"leap":"뛰어오르다; 도약",
"legal":"법적인, 합법적인",
"legend":"전설",
"leisure":"여가",
"lend":"빌려주다",
"liberal":"자유주의의, 관대한",
"liberty":"자유",
"license":"면허, 허가증",
"likely":"~할 것 같은",
"limb":"팔다리, 큰 가지",
"limit":"한계; 제한하다",
"linger":"오래 머물다, 남아 있다",
"link":"연결하다; 연결 고리",
"literal":"문자 그대로의",
"literature":"문학",
"litter":"쓰레기; 어지르다",
"load":"싣다; 짐, 부하",
"loan":"대출; 빌려주다",
"local":"지역의; 주민",
"locate":"위치시키다, 찾아내다",
"logic":"논리",
"loose":"헐거운, 느슨한",
"loyal":"충성스러운",
"luxury":"사치, 호화",
"magnificent":"장엄한, 훌륭한",
"maintain":"유지하다, 주장하다",
"major":"주요한; 전공",
"manage":"관리하다, 해내다",
"manner":"방식, 태도, 예절",
"manufacture":"제조하다; 제조",
"marine":"해양의",
"mass":"덩어리, 대중; 대량의",
"master":"숙달하다; 주인, 석사",
"match":"어울리다; 시합, 성냥",
"mature":"성숙한; 성숙하다",
"maximum":"최대의; 최대",
"means":"수단, 방법",
"measure":"측정하다; 조치, 척도",
"mechanism":"기제, 방법, 장치",
"medical":"의학의, 의료의",
"medium":"매체; 중간의",
"melt":"녹다, 녹이다",
"memorize":"암기하다",
"mental":"정신의",
"mention":"언급하다",
"merchant":"상인",
"mercy":"자비",
"mere":"단순한, ~에 불과한",
"merge":"합병하다, 합치다",
"merit":"장점, 가치",
"method":"방법",
"migrate":"이주하다, 이동하다",
"military":"군사의; 군대",
"mineral":"광물, 무기질",
"minimum":"최소의; 최소",
"minister":"장관, 목사",
"minor":"작은, 사소한; 미성년자",
"miracle":"기적",
"mislead":"오해하게 하다",
"mission":"임무, 사명",
"mixture":"혼합물",
"mobile":"이동식의, 기동성 있는",
"mock":"조롱하다; 모의의",
"moderate":"적당한, 온건한",
"modify":"수정하다, 변경하다",
"moist":"촉촉한",
"molecule":"분자",
"monitor":"감시하다; 화면",
"mood":"기분, 분위기",
"moral":"도덕적인; 교훈",
"motion":"움직임, 동작",
"motive":"동기",
"multiply":"곱하다, 증가시키다",
"murder":"살인; 살해하다",
"muscle":"근육",
"mutual":"상호간의, 서로의",
"mystery":"신비, 수수께끼",
"myth":"신화, 근거 없는 통념",
"naked":"벌거벗은",
"narrative":"이야기, 서술",
"narrow":"좁은; 좁히다",
"native":"토박이의, 원주민의",
"navigate":"항해하다, 길을 찾다",
"neat":"깔끔한, 정돈된",
"necessary":"필요한, 필수적인",
"negative":"부정적인, 음성의",
"neglect":"소홀히 하다; 방치",
"negotiate":"협상하다",
"nerve":"신경, 용기",
"neutral":"중립의",
"nevertheless":"그럼에도 불구하고",
"noble":"고귀한, 귀족의",
"norm":"규범, 표준",
"notable":"주목할 만한",
"note":"메모하다, 주목하다; 메모",
"notice":"알아차리다; 공지",
"notion":"개념, 생각",
"nourish":"영양분을 주다, 기르다",
"novel":"소설; 참신한",
"nuclear":"핵의, 원자력의",
"numerous":"수많은",
"nurture":"양육하다, 기르다",
"nutrition":"영양",
"obey":"복종하다, 따르다",
"object":"물체, 목적; 반대하다",
"observe":"관찰하다, 준수하다",
"obstacle":"장애물",
"obtain":"얻다, 획득하다",
"obvious":"명백한",
"occasion":"경우, 행사",
"occupy":"차지하다, 점령하다",
"occur":"일어나다, 발생하다",
"odd":"이상한, 홀수의",
"offend":"기분 상하게 하다, 위반하다",
"offer":"제공하다; 제안",
"official":"공식적인; 공무원",
"operate":"작동하다, 수술하다",
"opponent":"상대, 반대자",
"opportunity":"기회",
"oppose":"반대하다",
"optimistic":"낙관적인",
"option":"선택(권)",
"orbit":"궤도; 궤도를 돌다",
"order":"명령, 순서, 주문; 주문하다",
"ordinary":"평범한, 보통의",
"organ":"장기, 기관",
"organize":"조직하다, 정리하다",
"origin":"기원, 출신",
"outcome":"결과",
"output":"산출량, 출력",
"overall":"전반적인, 전체의",
"overcome":"극복하다",
"overlook":"간과하다, 내려다보다",
"overwhelm":"압도하다",
"owe":"빚지다, 신세를 지다",
"own":"자신의; 소유하다",
"oxygen":"산소"
});

Object.assign(window.VOCAB_DICT, {
"pace":"속도, 보조",
"pain":"고통, 아픔",
"panic":"공황; 공황 상태에 빠지다",
"parallel":"평행한; 유사점",
"partial":"부분적인, 편파적인",
"participate":"참여하다",
"particular":"특정한, 특별한",
"passion":"열정",
"passive":"수동적인",
"patent":"특허",
"path":"길, 경로",
"patience":"인내심",
"pattern":"양식, 무늬",
"peculiar":"독특한, 이상한",
"peer":"또래, 동료; 응시하다",
"penalty":"처벌, 벌금",
"perceive":"인지하다, 인식하다",
"perform":"수행하다, 공연하다",
"permanent":"영구적인",
"permit":"허가하다; 허가증",
"persist":"지속하다, 고집하다",
"perspective":"관점, 원근법",
"persuade":"설득하다",
"phase":"단계, 국면",
"phenomenon":"현상",
"philosophy":"철학",
"physical":"신체의, 물리적인",
"pile":"더미; 쌓다",
"pioneer":"개척자",
"pity":"연민, 유감",
"plain":"평범한, 명백한; 평원",
"planet":"행성",
"pleasant":"즐거운, 유쾌한",
"plenty":"풍부함, 충분함",
"plot":"줄거리, 음모; 계획하다",
"poison":"독; 독을 넣다",
"policy":"정책, 방침",
"polish":"닦다, 다듬다",
"political":"정치의",
"pollute":"오염시키다",
"popular":"인기 있는, 대중적인",
"population":"인구, 개체 수",
"portion":"부분, 몫",
"portray":"묘사하다, 그리다",
"pose":"제기하다, 자세를 취하다",
"positive":"긍정적인, 양성의",
"possess":"소유하다",
"postpone":"연기하다, 미루다",
"potential":"잠재적인; 잠재력",
"pour":"붓다, 쏟아지다",
"poverty":"가난, 빈곤",
"practical":"실용적인, 현실적인",
"praise":"칭찬하다; 칭찬",
"pray":"기도하다",
"precise":"정확한, 정밀한",
"predict":"예측하다",
"prefer":"선호하다",
"pregnant":"임신한",
"prejudice":"편견",
"preparation":"준비",
"prescribe":"처방하다, 규정하다",
"presence":"존재, 참석",
"preserve":"보존하다, 지키다",
"pressure":"압력, 압박",
"prestige":"명성, 위신",
"presume":"추정하다",
"pretend":"~인 척하다",
"prevail":"만연하다, 이기다",
"prevent":"막다, 예방하다",
"previous":"이전의",
"prey":"먹이, 사냥감",
"priest":"성직자, 사제",
"primary":"주요한, 초기의",
"prime":"주요한, 최상의",
"primitive":"원시적인",
"principal":"주요한; 교장",
"principle":"원칙, 원리",
"prior":"이전의, 우선하는",
"priority":"우선순위",
"privacy":"사생활",
"privilege":"특권",
"probable":"있을 법한",
"procedure":"절차",
"proceed":"진행하다, 나아가다",
"process":"과정; 처리하다",
"produce":"생산하다; 농산물",
"profession":"직업, 전문직",
"profit":"이익, 수익",
"profound":"심오한, 깊은",
"progress":"진전, 진보",
"prohibit":"금지하다",
"project":"계획, 과제; 투사하다",
"prominent":"저명한, 두드러진",
"promise":"약속하다; 약속",
"promote":"촉진하다, 승진시키다",
"prompt":"즉각적인; 촉발하다",
"pronounce":"발음하다, 선언하다",
"proof":"증거",
"proper":"적절한, 알맞은",
"property":"재산, 부동산, 속성",
"proportion":"비율, 부분",
"propose":"제안하다, 청혼하다",
"prospect":"전망, 가능성",
"protect":"보호하다",
"protest":"항의하다; 항의",
"prove":"증명하다, 입증하다",
"provide":"제공하다",
"province":"지방, 주",
"psychology":"심리학",
"public":"공공의; 대중",
"publish":"출판하다, 발표하다",
"punish":"처벌하다",
"purchase":"구매하다; 구매",
"pure":"순수한",
"purpose":"목적, 의도",
"pursue":"추구하다, 뒤쫓다",
"puzzle":"퍼즐; 당황하게 하다",
"qualify":"자격을 얻다, 자격을 주다",
"quality":"질, 품질, 자질",
"quantity":"양, 수량",
"quarrel":"다투다; 다툼",
"quit":"그만두다",
"quote":"인용하다; 인용문",
"race":"경주, 인종",
"radical":"급진적인, 근본적인",
"random":"무작위의",
"range":"범위; ~에 이르다",
"rank":"순위, 계급",
"rapid":"빠른, 신속한",
"rare":"드문, 희귀한",
"rate":"비율, 요금; 평가하다",
"rather":"오히려, 다소",
"raw":"날것의, 가공되지 않은",
"react":"반응하다",
"realize":"깨닫다, 실현하다",
"realm":"영역, 왕국",
"reason":"이유, 이성",
"rebel":"반란을 일으키다; 반역자",
"recall":"기억해 내다, 회수하다",
"receipt":"영수증, 수령",
"receive":"받다",
"recent":"최근의",
"recipe":"조리법, 비결",
"recognize":"알아보다, 인정하다",
"recommend":"추천하다, 권하다",
"recover":"회복하다, 되찾다",
"reduce":"줄이다, 감소시키다",
"refer":"언급하다, 참조하다",
"reflect":"반영하다, 반사하다, 숙고하다",
"reform":"개혁하다; 개혁",
"refuge":"피난처, 은신처",
"refuse":"거절하다",
"regard":"~로 여기다; 존경",
"region":"지역, 지방",
"register":"등록하다; 등록부",
"regret":"후회하다; 후회",
"regular":"정기적인, 규칙적인",
"regulate":"규제하다, 조절하다",
"reinforce":"강화하다, 보강하다",
"reject":"거절하다, 거부하다",
"relate":"관련시키다, 이야기하다",
"relative":"상대적인; 친척",
"release":"풀어주다, 공개하다",
"relevant":"관련 있는, 적절한",
"reliable":"믿을 만한",
"relief":"안도, 구호",
"religion":"종교",
"reluctant":"꺼리는, 마지못한",
"rely":"의존하다, 신뢰하다",
"remain":"남다, 여전히 ~이다",
"remark":"발언; 언급하다",
"remedy":"치료법, 해결책",
"remind":"상기시키다",
"remote":"먼, 외딴, 원격의",
"remove":"제거하다, 옮기다",
"render":"만들다, 제공하다",
"renew":"갱신하다, 재개하다",
"repair":"수리하다; 수리",
"repeat":"반복하다",
"replace":"대체하다, 교체하다",
"represent":"대표하다, 나타내다",
"reputation":"명성, 평판",
"request":"요청하다; 요청",
"require":"요구하다, 필요로 하다",
"rescue":"구조하다; 구조",
"research":"연구; 연구하다",
"resemble":"닮다",
"reserve":"예약하다, 비축하다; 비축물",
"reside":"거주하다",
"resist":"저항하다, 참다",
"resolve":"해결하다, 결심하다",
"resource":"자원, 재원",
"respect":"존경하다; 존경, 측면",
"respond":"반응하다, 대답하다",
"responsible":"책임이 있는",
"restore":"복원하다, 회복시키다",
"restrict":"제한하다",
"result":"결과; 결과로 생기다",
"resume":"재개하다",
"retain":"유지하다, 보유하다",
"retire":"은퇴하다",
"retreat":"후퇴하다; 후퇴",
"reveal":"드러내다, 밝히다",
"revenue":"수익, 세입",
"reverse":"뒤집다; 반대의",
"review":"검토하다, 복습하다; 후기",
"revise":"수정하다, 복습하다",
"revolution":"혁명, 회전",
"reward":"보상; 보상하다",
"rid":"제거하다, 없애다",
"ridiculous":"터무니없는, 우스꽝스러운",
"rigid":"엄격한, 뻣뻣한",
"riot":"폭동",
"ripe":"익은, 무르익은",
"risk":"위험; 위험을 무릅쓰다",
"ritual":"의식, 의례",
"roar":"포효하다; 포효",
"roast":"굽다",
"rob":"강탈하다, 털다",
"role":"역할",
"root":"뿌리, 근원",
"rough":"거친, 대략의",
"route":"경로, 노선",
"routine":"일상, 정해진 일; 일상적인",
"row":"줄, 열; 노를 젓다",
"royal":"왕실의",
"rub":"문지르다, 비비다",
"rude":"무례한",
"ruin":"파괴하다, 망치다; 폐허",
"rural":"시골의, 농촌의",
"rush":"돌진하다, 서두르다"
});

Object.assign(window.VOCAB_DICT, {
"sacred":"신성한",
"sacrifice":"희생; 희생하다",
"satellite":"위성",
"satisfy":"만족시키다",
"scale":"규모, 저울, 비늘",
"scan":"살펴보다, 훑어보다",
"scarce":"부족한, 드문",
"scatter":"흩뿌리다, 흩어지다",
"scene":"장면, 현장",
"scheme":"계획, 책략",
"scholar":"학자",
"scope":"범위, 여지",
"scream":"비명을 지르다",
"sculpture":"조각, 조각품",
"seal":"봉하다; 물개, 도장",
"secure":"안전한; 확보하다",
"seek":"찾다, 추구하다",
"seize":"붙잡다, 장악하다",
"seldom":"좀처럼 ~않다",
"select":"선택하다",
"sensitive":"민감한, 예민한",
"sentence":"문장, 형벌",
"separate":"분리하다; 별개의",
"sequence":"순서, 연속",
"series":"연속, 시리즈",
"session":"기간, 회기",
"settle":"정착하다, 해결하다",
"severe":"심각한, 혹독한",
"shade":"그늘, 색조",
"shallow":"얕은",
"shame":"수치심, 유감",
"shape":"모양; 형성하다",
"share":"공유하다; 몫, 주식",
"shed":"흘리다, 없애다; 헛간",
"shelter":"피난처, 보호소",
"shift":"이동하다; 변화, 교대",
"shrink":"줄어들다, 수축하다",
"sibling":"형제자매",
"sight":"시력, 광경",
"signal":"신호; 신호를 보내다",
"significant":"중요한, 상당한",
"similar":"비슷한",
"sincere":"진심 어린",
"situation":"상황",
"skeptical":"회의적인",
"skill":"기술, 기량",
"slave":"노예",
"slight":"약간의, 경미한",
"slope":"경사, 비탈",
"smooth":"매끄러운; 다듬다",
"soak":"적시다, 담그다",
"soar":"치솟다, 급등하다",
"sociable":"사교적인",
"society":"사회, 협회",
"soil":"토양, 흙",
"solar":"태양의",
"soldier":"군인",
"sole":"유일한; 발바닥",
"solid":"고체의, 단단한, 확실한",
"solution":"해결책, 용액",
"somewhat":"다소, 어느 정도",
"sophisticated":"정교한, 세련된",
"sorrow":"슬픔",
"source":"출처, 원천",
"span":"기간, 폭",
"spare":"여분의; 할애하다",
"species":"종",
"specific":"구체적인, 특정한",
"specimen":"표본, 견본",
"spectacular":"장관인, 극적인",
"speculate":"추측하다, 투기하다",
"sphere":"구, 영역",
"spill":"쏟다, 엎지르다",
"spin":"돌다, 회전하다",
"spirit":"정신, 영혼",
"split":"나누다, 쪼개다",
"spoil":"망치다, 상하게 하다",
"spot":"발견하다; 지점, 얼룩",
"spread":"퍼지다, 펼치다",
"stable":"안정적인; 마구간",
"stack":"쌓다; 더미",
"stain":"얼룩; 얼룩지게 하다",
"stare":"응시하다",
"startle":"깜짝 놀라게 하다",
"starve":"굶주리다",
"statistics":"통계",
"status":"지위, 상태",
"steady":"꾸준한, 안정된",
"steep":"가파른",
"stem":"줄기; 유래하다",
"stick":"붙이다, 고수하다; 막대기",
"stimulate":"자극하다, 촉진하다",
"stir":"휘젓다, 자극하다",
"stock":"재고, 주식",
"store":"저장하다; 가게",
"strain":"긴장, 부담; 혹사시키다",
"strategy":"전략",
"stream":"개울, 흐름",
"strength":"힘, 강점",
"stress":"스트레스, 강조; 강조하다",
"stretch":"뻗다, 늘이다",
"strict":"엄격한",
"strike":"치다, 파업하다; 파업",
"striking":"눈에 띄는, 인상적인",
"strive":"노력하다, 애쓰다",
"structure":"구조, 건축물",
"struggle":"분투하다; 투쟁",
"stubborn":"고집 센, 완고한",
"submit":"제출하다, 굴복하다",
"subsequent":"이후의, 다음의",
"substance":"물질, 실체",
"substitute":"대체하다; 대체물",
"subtle":"미묘한, 교묘한",
"succeed":"성공하다, 계승하다",
"sufficient":"충분한",
"suggest":"제안하다, 시사하다",
"suicide":"자살",
"suit":"어울리다, 맞다; 정장",
"summarize":"요약하다",
"superior":"우수한, 상급의",
"supply":"공급하다; 공급",
"support":"지지하다, 부양하다; 지원",
"suppose":"가정하다, 생각하다",
"suppress":"억압하다, 참다",
"surface":"표면",
"surgery":"수술",
"surplus":"잉여, 과잉",
"surrender":"항복하다; 항복",
"surround":"둘러싸다",
"survey":"조사; 조사하다",
"survive":"살아남다, 생존하다",
"suspect":"의심하다; 용의자",
"suspend":"중단하다, 매달다",
"sustain":"지속시키다, 지탱하다",
"swallow":"삼키다; 제비",
"swear":"맹세하다, 욕하다",
"sweat":"땀; 땀을 흘리다",
"sweep":"쓸다, 휩쓸다",
"swell":"부풀다, 붓다",
"swift":"신속한",
"symbol":"상징, 기호",
"sympathy":"동정, 공감",
"symptom":"증상, 징후",
"tackle":"다루다, 태클하다",
"talent":"재능",
"target":"목표, 표적",
"task":"과제, 임무",
"tease":"놀리다",
"technique":"기법, 기술",
"temper":"성질, 기분",
"temporary":"일시적인, 임시의",
"tempt":"유혹하다",
"tend":"~하는 경향이 있다, 돌보다",
"tender":"부드러운, 다정한",
"tense":"긴장한; 시제",
"terrify":"겁먹게 하다",
"territory":"영토, 지역",
"testify":"증언하다",
"theme":"주제",
"theory":"이론",
"therapy":"치료, 요법",
"thorough":"철저한",
"threat":"위협",
"thrive":"번성하다, 잘 자라다",
"throat":"목구멍",
"tide":"조수, 흐름",
"tidy":"깔끔한; 정돈하다",
"tight":"꽉 조이는, 팽팽한",
"timber":"목재",
"tiny":"아주 작은",
"tissue":"조직, 화장지",
"tolerate":"참다, 용인하다",
"toll":"통행료, 사상자 수",
"tone":"어조, 색조",
"tool":"도구",
"topic":"주제, 화제",
"torture":"고문; 고문하다",
"toss":"던지다",
"trace":"추적하다; 흔적",
"track":"추적하다; 길, 트랙",
"trade":"무역, 거래; 거래하다",
"tradition":"전통",
"traffic":"교통(량)",
"tragedy":"비극",
"trail":"오솔길, 자취",
"trait":"특성, 특징",
"transfer":"이동하다, 옮기다; 이전",
"transform":"변형시키다, 바꾸다",
"translate":"번역하다",
"transmit":"전송하다, 전염시키다",
"transparent":"투명한",
"transport":"수송하다; 수송",
"trap":"덫; 가두다",
"treasure":"보물; 소중히 여기다",
"treat":"다루다, 치료하다, 대접하다",
"tremble":"떨다",
"tremendous":"엄청난",
"trend":"경향, 추세",
"trial":"재판, 시도",
"tribe":"부족",
"trick":"속임수; 속이다",
"trigger":"촉발하다; 방아쇠",
"triumph":"승리",
"trivial":"사소한",
"troop":"군대, 병력",
"tropical":"열대의",
"trust":"신뢰; 신뢰하다",
"tuition":"수업료, 교습",
"tunnel":"터널",
"typical":"전형적인, 대표적인",
"ultimate":"궁극적인, 최후의",
"unique":"독특한, 유일한",
"unite":"연합하다, 통합하다",
"universal":"보편적인, 전 세계의",
"universe":"우주",
"unless":"~하지 않는 한",
"update":"갱신하다; 최신 정보",
"upset":"화난; 속상하게 하다",
"urban":"도시의",
"urge":"촉구하다; 충동",
"urgent":"긴급한",
"utility":"유용성, 공공 설비",
"utilize":"활용하다",
"vacant":"비어 있는, 공석의",
"vague":"모호한, 애매한",
"vain":"헛된, 허영심 있는",
"valid":"유효한, 타당한",
"value":"가치; 소중히 여기다",
"vanish":"사라지다",
"variety":"다양성, 종류",
"various":"다양한",
"vary":"다르다, 변하다",
"vast":"광대한, 막대한",
"vehicle":"차량, 수단",
"venture":"모험적 사업; 과감히 해보다",
"verbal":"언어의, 구두의",
"verify":"확인하다, 입증하다",
"version":"판, 버전",
"vertical":"수직의",
"vessel":"그릇, 선박, 혈관",
"veteran":"베테랑, 참전 용사",
"victim":"희생자, 피해자",
"viewpoint":"관점",
"violate":"위반하다, 침해하다",
"violence":"폭력",
"virtual":"가상의, 사실상의",
"virtue":"미덕, 장점",
"visible":"보이는, 눈에 띄는",
"vision":"시력, 비전",
"visual":"시각의",
"vital":"필수적인, 생명의",
"vivid":"생생한, 선명한",
"volume":"부피, 음량, 권",
"voluntary":"자발적인",
"vote":"투표하다; 투표",
"voyage":"항해",
"wage":"임금",
"wander":"돌아다니다, 방황하다",
"warn":"경고하다",
"warrant":"영장; 정당화하다",
"waste":"낭비하다; 낭비, 폐기물",
"weaken":"약화시키다",
"wealth":"부, 재산",
"weapon":"무기",
"weave":"짜다, 엮다",
"weed":"잡초",
"weigh":"무게가 나가다, 저울질하다",
"welfare":"복지, 안녕",
"whereas":"~인 반면에",
"whisper":"속삭이다; 속삭임",
"whole":"전체의; 전체",
"widespread":"널리 퍼진",
"wilderness":"황무지, 야생",
"willing":"기꺼이 하는",
"withdraw":"철회하다, 인출하다",
"withstand":"견디다, 저항하다",
"witness":"목격자; 목격하다",
"worship":"숭배하다; 숭배",
"worth":"~의 가치가 있는; 가치",
"wound":"상처; 상처를 입히다",
"wrap":"싸다, 포장하다",
"yield":"산출하다, 양보하다; 수확량",
"zone":"지역, 구역"
});

/* ─────────────────────────────────────────────────────────────
   기초 단어 — 사진에는 잔뜩 나오지만 단어장에 담을 이유는 없는 것들.
   기본값으로 화면에서 숨긴다. ('쉬운 단어 숨기기' 를 끄면 다시 보인다)
   ───────────────────────────────────────────────────────────── */
window.VOCAB_EASY = new Set(("a about above after again against all also always am an and " +
"another any are around as ask at away back be because been before being below best better between big " +
"both but buy by call came can cannot come could day did different do does doing don down each early " +
"eat end enough even ever every example eye face fact family far feel few find first five for found four " +
"friend from get girl give go going good got great group had hand happy has have he head hear help her " +
"here high him his home hour house how however i if in into is it its just keep kind know large last late " +
"learn leave left let life like little live long look lot love made make man many may me mean men might " +
"mind more most mother move much must my name near need never new next nice night no not now number of " +
"off often oh old on once one only open or other our out over own page paper part people place play please " +
"point put read ready real really right room run said same saw say school sea second see seem set she " +
"should show side since sit six small so some soon sound speak start state stay still stop story student " +
"such take talk teacher tell ten than thank that the their them then there these they thing think this " +
"those though three through time to today together too took top town try turn two under until up upon us " +
"use used very walk want war watch water way we week well went were what when where which while white who " +
"why will wish with without woman word work world would write year yes yet you young your").split(" "));

/* ─────────────────────────────────────────────────────────────
   낱말의 원형 찾기.

   두 갈래로 나눠 다룬다.

   · 굴절 — achieved · achieves · achieving 은 achieve 와 같은 말이다.
     단어장에는 원형 하나로 모아 담는다.
   · 파생 — movement 는 move 에서 나왔지만 다른 말이다.
     뜻은 원형에서 빌려 오되, 단어장에는 학생이 본 그대로 담는다.

   그래서 moving 을 담으면 move 가, movement 를 담으면 movement 가 남는다.
   ───────────────────────────────────────────────────────────── */

/* 규칙으로는 되돌릴 수 없는 굴절형 */
window.VOCAB_IRREGULAR = {
"am":"be","is":"be","are":"be","was":"be","were":"be","been":"be",
"has":"have","had":"have","does":"do","did":"do","done":"do",
"went":"go","gone":"go","made":"make","said":"say","saw":"see","seen":"see",
"took":"take","taken":"take","came":"come","got":"get","gotten":"get",
"gave":"give","given":"give","found":"find","thought":"think","told":"tell",
"became":"become","left":"leave","felt":"feel","brought":"bring",
"began":"begin","begun":"begin","kept":"keep","held":"hold",
"wrote":"write","written":"write","stood":"stand","heard":"hear",
"meant":"mean","met":"meet","ran":"run","paid":"pay","sat":"sit",
"spoke":"speak","spoken":"speak","led":"lead","grew":"grow","grown":"grow",
"lost":"lose","fell":"fall","fallen":"fall","sent":"send","built":"build",
"understood":"understand","drew":"draw","drawn":"draw",
"broke":"break","broken":"break","spent":"spend","rose":"rise","risen":"rise",
"drove":"drive","driven":"drive","bought":"buy","wore":"wear","worn":"wear",
"chose":"choose","chosen":"choose","taught":"teach","caught":"catch",
"ate":"eat","eaten":"eat","sold":"sell","threw":"throw","thrown":"throw",
"flew":"fly","flown":"fly","knew":"know","known":"know",
"forgot":"forget","forgotten":"forget","blew":"blow","blown":"blow",
"swam":"swim","swum":"swim","sang":"sing","sung":"sing",
"drank":"drink","drunk":"drink","rang":"ring","rung":"ring",
"slept":"sleep","hid":"hide","hidden":"hide","shot":"shoot",
"struck":"strike","stuck":"stick","won":"win","laid":"lay",
"dealt":"deal","slid":"slide","bit":"bite","bitten":"bite",
"rode":"ride","ridden":"ride","shook":"shake","shaken":"shake",
"stole":"steal","stolen":"steal","tore":"tear","torn":"tear",
"froze":"freeze","frozen":"freeze","arose":"arise","arisen":"arise",
"bore":"bear","borne":"bear","beaten":"beat","bent":"bend","bound":"bind",
"bled":"bleed","bred":"breed","dug":"dig","fed":"feed","fought":"fight",
"fled":"flee","forbade":"forbid","forbidden":"forbid",
"forgave":"forgive","forgiven":"forgive","hung":"hang","knelt":"kneel",
"lent":"lend","lit":"light","sank":"sink","sunk":"sink","sought":"seek",
"shone":"shine","shrank":"shrink","shrunk":"shrink","sped":"speed",
"spun":"spin","sprang":"spring","sprung":"spring","strove":"strive",
"swept":"sweep","swore":"swear","sworn":"swear","swung":"swing",
"wept":"weep","withdrew":"withdraw","withdrawn":"withdraw",
"woke":"wake","woken":"wake","wound":"wind","lain":"lie",

"children":"child","women":"woman","men":"man","feet":"foot","teeth":"tooth",
"mice":"mouse","geese":"goose","oxen":"ox","lives":"life","knives":"knife",
"wives":"wife","leaves":"leaf","wolves":"wolf","shelves":"shelf",
"halves":"half","calves":"calf","thieves":"thief","loaves":"loaf",
"selves":"self","criteria":"criterion","phenomena":"phenomenon",
"media":"medium","analyses":"analysis","bases":"basis","crises":"crisis",
"theses":"thesis","hypotheses":"hypothesis","indices":"index",
"matrices":"matrix","appendices":"appendix","curricula":"curriculum",
"bacteria":"bacterium","fungi":"fungus","cacti":"cactus",
"alumni":"alumnus","stimuli":"stimulus","radii":"radius","formulae":"formula",

"better":"good","best":"good","worse":"bad","worst":"bad",
"further":"far","furthest":"far","farther":"far","farthest":"far",
"elder":"old","eldest":"old"
};

var _vocabPush = function (c, s) { if (s && s.length >= 2 && c.indexOf(s) === -1) c.push(s); };

/* 굴절 꼬리 한 겹 벗기기 — 복수 · 시제 · 진행 */
window.vocabInflectForms = function (x) {
    var c = [], add = function (s) { _vocabPush(c, s); };
    var irr = window.VOCAB_IRREGULAR[x];
    if (irr) add(irr);

    if (x.endsWith("ies")  && x.length > 4) add(x.slice(0, -3) + "y");
    if (x.endsWith("ves")  && x.length > 4) { add(x.slice(0, -3) + "f"); add(x.slice(0, -3) + "fe"); }
    if (x.endsWith("es")   && x.length > 3) { add(x.slice(0, -2)); add(x.slice(0, -1)); }
    if (x.endsWith("s") && !x.endsWith("ss") && x.length > 3) add(x.slice(0, -1));

    if (x.endsWith("ied")  && x.length > 4) add(x.slice(0, -3) + "y");
    if (x.endsWith("ed")   && x.length > 3) { add(x.slice(0, -2)); add(x.slice(0, -1)); add(x.slice(0, -3)); }

    if (x.endsWith("ying") && x.length > 4) add(x.slice(0, -4) + "ie");
    if (x.endsWith("ing")  && x.length > 4) { add(x.slice(0, -3)); add(x.slice(0, -3) + "e"); add(x.slice(0, -4)); }
    return c;
};

/* 파생 꼬리 한 겹 벗기기 — 뜻만 빌려 올 자리 */
window.vocabDeriveForms = function (x) {
    var c = [], add = function (s) { _vocabPush(c, s); };
    var L = x.length;

    // 어찌씨
    if (x.endsWith("bly")   && L > 4) add(x.slice(0, -3) + "ble");
    if (x.endsWith("ily")   && L > 4) add(x.slice(0, -3) + "y");
    if (x.endsWith("ly")    && L > 4) add(x.slice(0, -2));

    // 사람 · 견주기
    if (x.endsWith("ier")   && L > 4) add(x.slice(0, -3) + "y");
    if (x.endsWith("iest")  && L > 5) add(x.slice(0, -4) + "y");
    if (x.endsWith("er")    && L > 4) { add(x.slice(0, -2)); add(x.slice(0, -1)); add(x.slice(0, -3)); }
    if (x.endsWith("est")   && L > 5) { add(x.slice(0, -3)); add(x.slice(0, -2)); add(x.slice(0, -4)); }
    if (x.endsWith("or")    && L > 5) { add(x.slice(0, -2)); add(x.slice(0, -2) + "e"); }
    if (x.endsWith("ist")   && L > 5) { add(x.slice(0, -3)); add(x.slice(0, -3) + "e"); }

    // 이름씨 만들기
    if (x.endsWith("iness")   && L > 6) add(x.slice(0, -5) + "y");
    if (x.endsWith("ness")    && L > 5) add(x.slice(0, -4));
    if (x.endsWith("ment")    && L > 5) { add(x.slice(0, -4)); add(x.slice(0, -4) + "e"); }
    if (x.endsWith("ship")    && L > 6) add(x.slice(0, -4));
    if (x.endsWith("hood")    && L > 6) add(x.slice(0, -4));
    if (x.endsWith("dom")     && L > 5) add(x.slice(0, -3));
    if (x.endsWith("th")      && L > 5) add(x.slice(0, -2));
    if (x.endsWith("ance")    && L > 5) { add(x.slice(0, -4)); add(x.slice(0, -4) + "e"); add(x.slice(0, -4) + "ant"); }
    if (x.endsWith("ence")    && L > 5) { add(x.slice(0, -4)); add(x.slice(0, -4) + "e"); add(x.slice(0, -4) + "ent"); }
    if (x.endsWith("ison")    && L > 5) add(x.slice(0, -4) + "e");
    if (x.endsWith("mission") && L > 7) add(x.slice(0, -7) + "mit");
    if (x.endsWith("ption")   && L > 6) { add(x.slice(0, -5) + "be"); add(x.slice(0, -4) + "e"); }
    if (x.endsWith("ation")   && L > 6) { add(x.slice(0, -5)); add(x.slice(0, -5) + "e"); add(x.slice(0, -5) + "ate"); }
    if (x.endsWith("ition")   && L > 6) { add(x.slice(0, -5) + "e"); add(x.slice(0, -5) + "ize"); }
    if (x.endsWith("sion")    && L > 5) { add(x.slice(0, -4) + "de"); add(x.slice(0, -4) + "d"); add(x.slice(0, -3) + "e"); }
    if (x.endsWith("tion")    && L > 5) { add(x.slice(0, -3) + "e"); add(x.slice(0, -4)); }
    if (x.endsWith("ion")     && L > 5) { add(x.slice(0, -3)); add(x.slice(0, -3) + "e"); }
    if (x.endsWith("ility")   && L > 6) { add(x.slice(0, -5) + "le"); add(x.slice(0, -5)); }
    if (x.endsWith("ity")     && L > 5) { add(x.slice(0, -3)); add(x.slice(0, -3) + "e"); }
    if (x.endsWith("y")       && L > 5) { add(x.slice(0, -1)); add(x.slice(0, -1) + "e"); }

    // 그림씨 만들기
    if (x.endsWith("ful")   && L > 4) { add(x.slice(0, -3)); add(x.slice(0, -3) + "e"); }
    if (x.endsWith("less")  && L > 5) add(x.slice(0, -4));
    if (x.endsWith("able")  && L > 5) { add(x.slice(0, -4)); add(x.slice(0, -4) + "e"); }
    if (x.endsWith("ible")  && L > 5) { add(x.slice(0, -4)); add(x.slice(0, -4) + "e"); }
    if (x.endsWith("ical")  && L > 5) { add(x.slice(0, -4) + "y"); add(x.slice(0, -2)); add(x.slice(0, -4)); }
    if (x.endsWith("istic") && L > 6) { add(x.slice(0, -5)); add(x.slice(0, -3)); }
    if (x.endsWith("ician") && L > 6) { add(x.slice(0, -4) + "c"); add(x.slice(0, -5) + "ics"); }
    if (x.endsWith("ology") && L > 7) add(x.slice(0, -5));
    if (x.endsWith("ous")   && L > 5) { add(x.slice(0, -3)); add(x.slice(0, -3) + "e"); add(x.slice(0, -4) + "y"); }
    if (x.endsWith("ive")   && L > 4) { add(x.slice(0, -3)); add(x.slice(0, -3) + "e"); }
    if (x.endsWith("al")    && L > 4) { add(x.slice(0, -2)); add(x.slice(0, -2) + "e"); }
    if (x.endsWith("ic")    && L > 4) { add(x.slice(0, -2)); add(x.slice(0, -2) + "y"); }
    if (x.endsWith("en")    && L > 5) { add(x.slice(0, -2)); add(x.slice(0, -1)); }

    // 움직씨 만들기
    if (x.endsWith("ize")   && L > 5) { add(x.slice(0, -3)); add(x.slice(0, -3) + "y"); }
    if (x.endsWith("ise")   && L > 5) add(x.slice(0, -3));
    if (x.endsWith("ify")   && L > 5) { add(x.slice(0, -3)); add(x.slice(0, -3) + "y"); }
    return c;
};

/* 꼬리를 여러 겹 벗겨 나오는 후보를 모두 모은다.
   carefully → careful → care 처럼 두세 겹인 말이 있다. */
var _vocabClosure = function (seeds, step, rounds) {
    var out = [], frontier = seeds.slice(), r, next;
    for (r = 0; r < rounds && frontier.length && out.length < 80; r++) {
        next = [];
        frontier.forEach(function (x) {
            step(x).forEach(function (cand) {
                if (seeds.indexOf(cand) === -1 && out.indexOf(cand) === -1) { out.push(cand); next.push(cand); }
            });
        });
        frontier = next;
    }
    return out;
};

var _vocabClean = function (raw) { return String(raw || "").toLowerCase().replace(/[^a-z]/g, ""); };

window.vocabInflectClosure = function (w) { return _vocabClosure([w], window.vocabInflectForms, 2); };

/* 후보 전부 — 쉬운 단어 판별이 아니라 넓게 훑어야 할 때 쓴다 */
window.vocabBaseForms = function (raw) {
    var w = _vocabClean(raw);
    if (!w) return [];
    var seeds = [w].concat(window.vocabInflectClosure(w));
    return seeds.concat(_vocabClosure(seeds, window.vocabDeriveForms, 3));
};

/* 뜻 찾기.
   찾은 자리에 따라 단어장에 남길 낱말이 달라진다.
     쓴 그대로 있으면 → 그대로
     굴절만 벗겨 찾으면 → 원형으로 (achieved → achieve)
     파생까지 벗겨 찾으면 → 쓴 그대로 두고 뜻만 (movement 는 movement) */
window.vocabLookup = function (raw) {
    var dict = window.VOCAB_DICT || {};
    var w = _vocabClean(raw);
    if (!w) return null;
    if (dict[w]) return { base: w, meaning: dict[w], via: "exact" };

    var inf = window.vocabInflectClosure(w), i, j;
    for (i = 0; i < inf.length; i++) {
        if (dict[inf[i]]) return { base: inf[i], meaning: dict[inf[i]], via: "inflect" };
    }

    var seeds = [w].concat(inf);
    for (i = 0; i < seeds.length; i++) {
        var der = _vocabClosure([seeds[i]], window.vocabDeriveForms, 3);
        for (j = 0; j < der.length; j++) {
            if (dict[der[j]]) return { base: seeds[i], meaning: dict[der[j]], via: "derive" };
        }
    }
    return null;
};

/* 기초 단어인지 — 굴절만 되돌려서 본다.
   movement 를 move 로 되돌려 '쉬운 단어' 로 묶어 버리면 안 되기 때문이다. */
window.vocabIsEasy = function (raw) {
    var easy = window.VOCAB_EASY;
    var w = _vocabClean(raw);
    if (!w) return false;
    if (easy.has(w)) return true;
    var inf = window.vocabInflectClosure(w), i;
    for (i = 0; i < inf.length; i++) if (easy.has(inf[i])) return true;
    return false;
};

/* 위 목록에서 빠졌지만 지문에 자주 나오는 기본 단어들 보충 */
Object.assign(window.VOCAB_DICT, {
"afterward":"그 후에",
"agent":"대리인, 요원",
"amaze":"놀라게 하다",
"anger":"분노",
"area":"지역, 면적, 분야",
"art":"예술, 미술",
"bank":"은행, 둑",
"base":"기초; ~에 근거를 두다",
"beauty":"아름다움, 미인",
"body":"몸, 신체, 단체",
"book":"책; 예약하다",
"brain":"뇌, 두뇌",
"branch":"가지, 지점, 분야",
"break":"깨다, 부수다; 휴식",
"bright":"밝은, 총명한",
"bring":"가져오다, 데려오다",
"build":"짓다, 세우다",
"business":"사업, 일",
"care":"돌봄, 관심; 신경 쓰다",
"carry":"나르다, 지니다",
"catch":"잡다, 붙잡다",
"cause":"원인; 야기하다",
"change":"바꾸다; 변화",
"check":"확인하다; 점검",
"child":"아이, 자녀",
"choose":"선택하다, 고르다",
"city":"도시",
"class":"수업, 계층, 학급",
"clean":"깨끗한; 청소하다",
"clear":"명확한, 맑은; 치우다",
"close":"닫다; 가까운",
"color":"색; 색칠하다",
"company":"회사, 동료",
"computer":"컴퓨터",
"cook":"요리하다; 요리사",
"cost":"비용; 비용이 들다",
"country":"국가, 시골",
"cut":"자르다; 삭감",
"danger":"위험",
"dark":"어두운",
"death":"죽음",
"decision":"결정",
"deep":"깊은",
"difficulty":"어려움, 곤란",
"doctor":"의사, 박사",
"door":"문",
"draw":"그리다, 끌다",
"dream":"꿈; 꿈꾸다",
"drive":"운전하다, 몰아가다",
"drop":"떨어뜨리다; 방울",
"earth":"지구, 흙",
"easy":"쉬운",
"effort":"노력",
"energy":"에너지, 활력",
"enjoy":"즐기다",
"enter":"들어가다, 입력하다",
"event":"사건, 행사",
"fall":"떨어지다; 가을",
"fast":"빠른; 빨리",
"fear":"두려움; 두려워하다",
"field":"들판, 분야",
"fight":"싸우다; 싸움",
"fill":"채우다",
"fire":"불; 해고하다",
"fish":"물고기; 낚시하다",
"fit":"맞다; 건강한",
"fix":"고치다, 고정하다",
"floor":"바닥, 층",
"fly":"날다; 파리",
"follow":"따르다, 뒤따르다",
"food":"음식",
"foot":"발, 피트",
"forest":"숲",
"forget":"잊다",
"free":"자유로운, 무료의",
"fresh":"신선한",
"front":"앞; 앞의",
"fun":"재미; 재미있는",
"game":"게임, 경기",
"garden":"정원",
"glass":"유리, 잔",
"government":"정부",
"green":"초록의; 환경친화적인",
"grow":"자라다, 기르다",
"guess":"추측하다",
"half":"절반",
"hard":"어려운, 단단한; 열심히",
"health":"건강",
"heart":"심장, 마음",
"heat":"열; 데우다",
"heavy":"무거운",
"hold":"잡다, 개최하다",
"hope":"희망; 희망하다",
"hospital":"병원",
"hot":"뜨거운, 더운",
"human":"인간의; 인간",
"idea":"생각, 아이디어",
"important":"중요한",
"information":"정보",
"interest":"관심, 이자",
"job":"일자리, 직업",
"join":"참여하다, 결합하다",
"joy":"기쁨",
"jump":"뛰다",
"key":"열쇠; 핵심적인",
"kill":"죽이다",
"king":"왕",
"land":"땅; 착륙하다",
"language":"언어",
"laugh":"웃다",
"law":"법",
"lay":"놓다, 눕히다",
"lead":"이끌다; 납",
"level":"수준, 단계",
"library":"도서관",
"light":"빛; 가벼운",
"line":"선, 줄",
"list":"목록; 나열하다",
"listen":"듣다",
"lose":"잃다, 지다",
"loud":"시끄러운",
"low":"낮은",
"luck":"운",
"machine":"기계",
"map":"지도",
"mark":"표시하다; 자국, 점수",
"market":"시장",
"marry":"결혼하다",
"matter":"문제; 중요하다",
"meet":"만나다",
"message":"메시지",
"middle":"중간; 중간의",
"milk":"우유",
"million":"백만",
"minute":"분, 잠깐",
"miss":"놓치다, 그리워하다",
"mistake":"실수",
"model":"모형, 모델",
"moment":"순간",
"money":"돈",
"month":"달, 월",
"moon":"달",
"morning":"아침",
"mountain":"산",
"mouth":"입",
"music":"음악",
"nature":"자연, 본성",
"news":"소식, 뉴스",
"north":"북쪽",
"note":"메모; 주목하다",
"nothing":"아무것도 아닌 것",
"office":"사무실, 관직",
"oil":"기름, 석유",
"paint":"칠하다; 물감",
"parent":"부모",
"park":"공원; 주차하다",
"party":"파티, 정당",
"pass":"통과하다, 건네주다",
"past":"과거; 지난",
"pay":"지불하다; 급여",
"peace":"평화",
"person":"사람",
"phone":"전화",
"photo":"사진",
"picture":"그림, 사진",
"piece":"조각, 부분",
"plan":"계획; 계획하다",
"plant":"식물; 심다, 공장",
"pocket":"주머니",
"police":"경찰",
"poor":"가난한, 서투른",
"power":"힘, 권력, 전력",
"practice":"연습; 연습하다",
"present":"현재의; 선물; 발표하다",
"press":"누르다; 언론",
"price":"가격",
"print":"인쇄하다",
"prize":"상, 상품",
"problem":"문제",
"push":"밀다",
"question":"질문; 의문을 갖다",
"quick":"빠른",
"quiet":"조용한",
"rain":"비; 비가 오다",
"raise":"올리다, 기르다, 모으다",
"reach":"도달하다, 닿다",
"record":"기록하다; 기록, 음반",
"red":"빨간",
"remember":"기억하다",
"repeat":"반복하다",
"report":"보고하다; 보고서",
"rest":"휴식; 나머지",
"return":"돌아오다; 반환",
"rice":"쌀, 밥",
"rich":"부유한, 풍부한",
"ride":"타다",
"ring":"반지; 울리다",
"rise":"오르다; 상승",
"river":"강",
"road":"길, 도로",
"rock":"바위; 흔들다",
"round":"둥근; 한 회",
"rule":"규칙; 통치하다",
"safe":"안전한; 금고",
"sale":"판매, 할인",
"salt":"소금",
"save":"구하다, 저축하다",
"science":"과학",
"score":"점수; 득점하다",
"search":"검색하다; 수색",
"season":"계절, 시기",
"seat":"좌석",
"sell":"팔다",
"send":"보내다",
"sense":"감각, 의미; 느끼다",
"serve":"제공하다, 봉사하다",
"service":"서비스, 봉사",
"shake":"흔들다",
"sharp":"날카로운",
"sheet":"장, 시트",
"ship":"배; 수송하다",
"shoot":"쏘다, 촬영하다",
"shop":"가게; 쇼핑하다",
"short":"짧은, 부족한",
"shout":"외치다",
"sign":"기호, 표지판; 서명하다",
"silence":"침묵, 고요",
"simple":"단순한, 간단한",
"sing":"노래하다",
"skin":"피부",
"sky":"하늘",
"sleep":"자다; 잠",
"slow":"느린",
"smart":"똑똑한",
"smell":"냄새; 냄새가 나다",
"smile":"미소; 미소 짓다",
"snow":"눈; 눈이 오다",
"soft":"부드러운",
"song":"노래",
"south":"남쪽",
"space":"공간, 우주",
"special":"특별한",
"sport":"스포츠, 운동",
"spring":"봄, 샘, 용수철",
"stand":"서다, 견디다",
"star":"별, 스타",
"step":"단계, 걸음",
"stone":"돌",
"strange":"이상한, 낯선",
"street":"거리",
"strong":"강한, 튼튼한",
"study":"공부하다; 연구",
"stupid":"어리석은",
"success":"성공",
"sudden":"갑작스러운",
"sugar":"설탕",
"summer":"여름",
"sun":"태양",
"sweet":"달콤한",
"swim":"수영하다",
"table":"탁자, 표",
"teach":"가르치다",
"team":"팀",
"tear":"눈물; 찢다",
"technology":"기술, 과학기술",
"test":"시험; 시험하다",
"thick":"두꺼운, 짙은",
"thin":"얇은, 마른",
"thought":"생각",
"throw":"던지다",
"tired":"피곤한, 지친",
"touch":"만지다; 접촉",
"train":"기차; 훈련하다",
"travel":"여행하다; 여행",
"tree":"나무",
"trouble":"문제, 곤란",
"true":"사실인, 진실한",
"understand":"이해하다",
"village":"마을",
"visit":"방문하다; 방문",
"voice":"목소리",
"wait":"기다리다",
"wake":"깨다, 깨우다",
"wall":"벽",
"warm":"따뜻한",
"wash":"씻다",
"weak":"약한",
"wear":"입다, 착용하다",
"weather":"날씨",
"weight":"무게, 체중",
"west":"서쪽",
"wide":"넓은",
"wild":"야생의, 거친",
"wind":"바람",
"window":"창문",
"winter":"겨울",
"wise":"현명한",
"wonder":"궁금해하다; 경이",
"wood":"나무, 목재",
"worry":"걱정하다; 걱정",
"wrong":"틀린, 잘못된"
});

Object.assign(window.VOCAB_DICT, {
"goal":"목표, 골",
"remarkable":"놀라운, 주목할 만한",
"researcher":"연구자",
"persistence":"끈기, 지속",
"consistent":"일관된, 한결같은",
"significantly":"상당히, 크게",
"participant":"참가자",
"outcome":"결과",
"attitude":"태도, 자세",
"perception":"인식, 지각",
"motivation":"동기 부여",
"strategy":"전략",
"efficiency":"효율성",
"flexibility":"유연성",
"awareness":"인식, 자각",
"exposure":"노출",
"tendency":"경향",
"assumption":"가정, 추정",
"consequence":"결과, 영향",
"implication":"함의, 영향",
"framework":"틀, 체계",
"principle":"원칙, 원리",
"phenomenon":"현상",
"criterion":"기준",
"analysis":"분석",
"evidence":"증거",
"argument":"논거, 논쟁",
"conclusion":"결론",
"summary":"요약",
"paragraph":"문단, 단락",
"passage":"지문, 통로",
"vocabulary":"어휘",
"grammar":"문법",
"sentence":"문장, 형벌",
"meaning":"의미, 뜻",
"translation":"번역"
});

/* ─────────────────────────────────────────────────────────────
   기초 단어.

   쉬운 말이라 뜻을 안 달아 뒀었는데, 파생어가 뜻을 빌려 갈 자리가 없어졌다.
   move 에 뜻이 없으면 movement 도 뜻을 못 찾는다. 그래서 여기서 채운다.
   화면에서는 여전히 '쉬운 단어' 로 묶여 접혀 있다.

   이미 적어 둔 뜻은 건드리지 않는다.
   ───────────────────────────────────────────────────────────── */
(function (extra) {
    var d = window.VOCAB_DICT;
    Object.keys(extra).forEach(function (k) { if (!d[k]) d[k] = extra[k]; });
})({
"a":"하나의","about":"~에 대하여","above":"~ 위에","after":"~ 뒤에","again":"다시",
"against":"~에 맞서","all":"모두","also":"또한","always":"언제나","am":"~이다",
"an":"하나의","and":"그리고","another":"또 하나의","any":"어떤","are":"~이다",
"around":"주위에","ask":"묻다, 부탁하다","at":"~에","away":"떨어져","back":"뒤, 등",
"be":"~이다, 있다","because":"왜냐하면","been":"be의 과거분사","before":"~ 앞에, 전에",
"being":"존재","below":"~ 아래에","best":"가장 좋은","better":"더 좋은",
"between":"~ 사이에","big":"큰","both":"둘 다","but":"그러나","buy":"사다",
"by":"~에 의해, ~ 옆에","call":"부르다, 전화하다","came":"come의 과거",
"can":"~할 수 있다","cannot":"~할 수 없다","come":"오다","could":"~할 수 있었다",
"day":"날, 하루","did":"do의 과거","different":"다른","do":"하다","does":"do의 3인칭",
"doing":"하는 중","don":"~하지 않다 (don't)","down":"아래로","each":"각각의",
"early":"이른, 일찍","eat":"먹다","end":"끝, 끝나다","enough":"충분한",
"even":"심지어, ~조차","ever":"언젠가, 한 번이라도","every":"모든","example":"예, 보기",
"eye":"눈","face":"얼굴, 마주하다","fact":"사실","family":"가족","far":"먼, 멀리",
"feel":"느끼다","few":"몇 안 되는","find":"찾다, 알아내다","first":"첫 번째의",
"five":"다섯","for":"~을 위해, ~ 동안","found":"find의 과거","four":"넷","friend":"친구",
"from":"~에서, ~로부터","get":"얻다, 되다","girl":"소녀","give":"주다","go":"가다",
"going":"가는 중","good":"좋은","got":"get의 과거","great":"훌륭한, 큰","group":"무리, 집단",
"had":"have의 과거","hand":"손","happy":"행복한","has":"have의 3인칭","have":"가지다",
"he":"그","head":"머리","hear":"듣다","help":"돕다, 도움","her":"그녀의","here":"여기",
"high":"높은","him":"그를","his":"그의","home":"집","hour":"시간","house":"집",
"how":"어떻게","however":"그러나","i":"나","if":"만약","in":"~ 안에","into":"~ 안으로",
"is":"~이다","it":"그것","its":"그것의","just":"그저, 막","keep":"계속하다, 지키다",
"kind":"종류; 친절한","know":"알다","large":"큰","last":"마지막의, 지난","late":"늦은",
"learn":"배우다","leave":"떠나다, 남기다","left":"왼쪽; leave의 과거","let":"~하게 하다",
"life":"삶, 생명","like":"좋아하다; ~처럼","little":"작은, 조금","live":"살다",
"long":"긴, 오래","look":"보다, ~처럼 보이다","lot":"많음","love":"사랑하다",
"made":"make의 과거","make":"만들다","man":"남자, 사람","many":"많은","may":"~일지 모른다",
"me":"나를","mean":"의미하다; 못된","men":"man의 복수","might":"~일지 모른다",
"mind":"마음; 꺼리다","more":"더 많은","most":"가장 많은","mother":"어머니",
"move":"움직이다","much":"많은","must":"~해야 한다","my":"나의","name":"이름",
"near":"가까운","need":"필요하다","never":"결코 ~않다","new":"새로운","next":"다음의",
"nice":"좋은, 멋진","night":"밤","no":"아니","not":"~ 아니다","now":"지금",
"number":"숫자, 수","of":"~의","off":"떨어져, 꺼진","often":"자주","oh":"아",
"old":"늙은, 오래된","on":"~ 위에","once":"한 번, 옛날에","one":"하나",
"only":"오직, 유일한","open":"열다, 열린","or":"또는","other":"다른","our":"우리의",
"out":"밖으로","over":"~ 너머, 끝난","page":"쪽, 면","paper":"종이, 논문","part":"부분",
"people":"사람들","place":"장소, 놓다","play":"놀다, 연주하다","please":"부디; 기쁘게 하다",
"point":"점, 요점; 가리키다","put":"놓다","read":"읽다","ready":"준비된","real":"진짜의",
"really":"정말로","right":"옳은; 오른쪽","room":"방, 공간","run":"달리다, 운영하다",
"said":"say의 과거","same":"같은","saw":"see의 과거; 톱","say":"말하다","school":"학교",
"sea":"바다","second":"두 번째의; 초","see":"보다","seem":"~처럼 보이다",
"set":"놓다, 정하다","she":"그녀","should":"~해야 한다","show":"보여 주다",
"side":"쪽, 옆면","since":"~ 이후로, ~ 때문에","sit":"앉다","six":"여섯","small":"작은",
"so":"그래서, 그렇게","some":"몇몇의","soon":"곧","sound":"소리; ~처럼 들리다",
"speak":"말하다","start":"시작하다","state":"상태, 주; 말하다","stay":"머무르다",
"still":"여전히; 가만한","stop":"멈추다","story":"이야기","student":"학생","such":"그런",
"take":"가지다, 데려가다","talk":"이야기하다","teacher":"선생님","tell":"말하다","ten":"열",
"than":"~보다","thank":"고마워하다","that":"저것, 그","the":"그","their":"그들의",
"them":"그들을","then":"그때, 그러고 나서","there":"거기","these":"이것들","they":"그들",
"thing":"것, 물건","think":"생각하다","this":"이것","those":"저것들","though":"~이지만",
"three":"셋","through":"~을 통해","time":"시간, 번","to":"~로, ~에게","today":"오늘",
"together":"함께","too":"너무; 또한","took":"take의 과거","top":"꼭대기, 맨 위",
"town":"마을","try":"해 보다","turn":"돌다, 바뀌다; 차례","two":"둘","under":"~ 아래에",
"until":"~까지","up":"위로","upon":"~ 위에","us":"우리를","use":"쓰다, 사용하다",
"used":"쓰인; ~하곤 했다","very":"매우","walk":"걷다","want":"원하다","war":"전쟁",
"watch":"지켜보다; 손목시계","water":"물","way":"길, 방법","we":"우리","week":"주",
"well":"잘; 우물","went":"go의 과거","were":"be의 과거","what":"무엇","when":"언제",
"where":"어디","which":"어느","while":"~하는 동안","white":"흰","who":"누구","why":"왜",
"will":"~할 것이다","wish":"바라다","with":"~와 함께","without":"~ 없이","woman":"여자",
"word":"낱말, 말","work":"일하다, 작동하다","world":"세계","would":"~할 것이다",
"write":"쓰다","year":"해, 년","yes":"예","yet":"아직; 그러나","you":"너","young":"젊은",
"your":"너의",

/* 규칙으로는 원형을 못 찾는 말, 그리고 자주 나오는데 빠져 있던 말 */
"although":"비록 ~일지라도","data":"자료, 데이터","medium":"매체; 중간의",
"basis":"기초, 근거","emphasis":"강조","thesis":"논제, 논문","crisis":"위기",
"hypothesis":"가설","index":"색인, 지표","matrix":"행렬, 모체","curriculum":"교육 과정",
"scientist":"과학자","scientific":"과학의","explanation":"설명",
"description":"설명, 묘사","comparison":"비교","recognition":"인식, 인정",
"discovery":"발견","possible":"가능한","possibility":"가능성","probable":"있음 직한",
"final":"마지막의","statement":"진술, 말","movement":"움직임, 운동",
"confidence":"자신감, 확신","politics":"정치","politician":"정치인","musician":"음악가",
"artistic":"예술의","psychology":"심리학","biology":"생물학","technology":"기술",
"observation":"관찰","impression":"인상","expression":"표현","permission":"허락",
"admission":"입장, 인정","majority":"다수","minority":"소수",

/* 앞가지가 붙어 뜻이 뒤집히는 말은 따로 적는다.
   unable 을 able 로 되돌려 '할 수 있는' 이라고 알려 주면 정반대가 되기 때문이다. */
"unable":"~할 수 없는","unknown":"알려지지 않은","unusual":"흔치 않은",
"unhappy":"불행한","unfair":"불공평한","unlikely":"~할 것 같지 않은",
"unnecessary":"불필요한","uncomfortable":"불편한","unexpected":"뜻밖의",
"unfortunately":"불행히도","incorrect":"틀린","impossible":"불가능한",
"impatient":"참을성 없는","independent":"독립적인","invisible":"눈에 보이지 않는",
"informal":"격식 없는","inexpensive":"비싸지 않은","dishonest":"정직하지 않은",
"disagree":"동의하지 않다","disappear":"사라지다","disadvantage":"불리한 점",
"dislike":"싫어하다","misunderstand":"오해하다","mistake":"실수","misuse":"잘못 쓰다",

/* 글을 잇는 말 */
"nevertheless":"그럼에도 불구하고","therefore":"그러므로","furthermore":"게다가",
"moreover":"더욱이","otherwise":"그렇지 않으면","whereas":"반면에",
"whether":"~인지 아닌지","despite":"~에도 불구하고","throughout":"~ 내내",
"somewhat":"다소","somehow":"어떻게든","anyway":"어쨌든","instead":"대신에",
"besides":"게다가","meanwhile":"그동안에","thus":"따라서","hence":"그러므로"
});

/* 불규칙형이 가리키는 원형인데 뜻이 비어 있던 낱말들 */
(function (extra) {
    var d = window.VOCAB_DICT;
    Object.keys(extra).forEach(function (k) { if (!d[k]) d[k] = extra[k]; });
})({
"become":"~이 되다","begin":"시작하다","spend":"쓰다, 보내다","blow":"불다",
"drink":"마시다","win":"이기다","slide":"미끄러지다","bite":"물다","steal":"훔치다",
"freeze":"얼다","beat":"두드리다, 이기다","bend":"구부리다","bleed":"피를 흘리다",
"dig":"파다","hang":"걸다, 매달다","kneel":"무릎 꿇다","sink":"가라앉다",
"shine":"빛나다","speed":"빠르기; 서두르다","swing":"흔들리다","weep":"울다",
"lie":"눕다; 거짓말하다","bad":"나쁜",
"tooth":"이, 치아","mouse":"쥐","goose":"거위","ox":"황소","knife":"칼",
"wife":"아내","leaf":"잎","wolf":"늑대","shelf":"선반","calf":"송아지",
"thief":"도둑","loaf":"덩어리","self":"자기 자신","appendix":"부록, 맹장",
"bacterium":"세균","fungus":"곰팡이, 균류","cactus":"선인장","alumnus":"졸업생",
"stimulus":"자극","radius":"반지름","formula":"공식"
});

/* 흔한데 빠져 있던 일상어 */
(function (extra) {
    var d = window.VOCAB_DICT;
    Object.keys(extra).forEach(function (k) { if (!d[k]) d[k] = extra[k]; });
})({
"father":"아버지","brother":"형제","sister":"자매","parent":"부모","son":"아들",
"daughter":"딸","baby":"아기","child":"아이","aunt":"이모, 고모","uncle":"삼촌",
"cousin":"사촌","husband":"남편","grandmother":"할머니","grandfather":"할아버지",

"corner":"모퉁이","member":"구성원","answer":"대답, 답하다","center":"중심",
"finger":"손가락","silver":"은","dinner":"저녁 식사","lunch":"점심","breakfast":"아침 식사",
"kitchen":"부엌","chicken":"닭, 닭고기","curtain":"커튼","captain":"주장, 선장",
"lantern":"등불","golden":"금빛의","modern":"현대의","eastern":"동쪽의","western":"서쪽의",
"northern":"북쪽의","southern":"남쪽의","suffer":"고통받다","contest":"대회, 겨루기",

"history":"역사","animal":"동물","plant":"식물, 심다","total":"전체의, 합계",
"metal":"금속","rival":"경쟁자","magic":"마법","plastic":"플라스틱","national":"국가의",
"army":"군대","navy":"해군","copy":"복사하다, 사본",

"angry":"화난","hungry":"배고픈","thirsty":"목마른","pretty":"예쁜","ugly":"못생긴",
"serious":"진지한, 심각한","anxious":"불안한, 간절한","either":"둘 중 하나",
"neither":"둘 다 아닌","whenever":"~할 때마다","wherever":"어디든지",

"morning":"아침","afternoon":"오후","evening":"저녁","yesterday":"어제",
"tomorrow":"내일","tonight":"오늘 밤","month":"달, 월","weekend":"주말",
"season":"계절","spring":"봄; 튀어 오르다","summer":"여름","autumn":"가을","winter":"겨울",

"body":"몸","hair":"머리카락","arm":"팔","leg":"다리","hands":"손",
"heart":"심장, 마음","brain":"뇌","blood":"피","bone":"뼈","skin":"피부",
"voice":"목소리","smile":"미소 짓다","cry":"울다","laugh":"웃다","sleep":"자다",

"food":"음식","rice":"쌀, 밥","bread":"빵","meat":"고기","fruit":"과일",
"vegetable":"채소","milk":"우유","egg":"달걀","salt":"소금","sugar":"설탕",
"taste":"맛; 맛보다",

"city":"도시","village":"마을","country":"나라, 시골","street":"거리","road":"길",
"bridge":"다리","building":"건물","station":"역","airport":"공항","hotel":"호텔",
"market":"시장","shop":"가게","store":"가게; 저장하다","library":"도서관",
"hospital":"병원","church":"교회","park":"공원","farm":"농장","garden":"정원",

"train":"기차; 훈련하다","bus":"버스","car":"자동차","bike":"자전거","plane":"비행기",
"ship":"배","boat":"배","travel":"여행하다","trip":"여행","journey":"여정",

"money":"돈","price":"값","cost":"비용; 비용이 들다","cheap":"싼","expensive":"비싼",
"rich":"부유한","poor":"가난한","pay":"지불하다","sell":"팔다","spend":"쓰다",

"weather":"날씨","rain":"비; 비가 오다","snow":"눈","wind":"바람","cloud":"구름",
"sun":"해","moon":"달","star":"별","sky":"하늘","earth":"지구, 땅",
"fire":"불","ice":"얼음","hot":"뜨거운","cold":"차가운","warm":"따뜻한","cool":"시원한",
"dry":"마른","wet":"젖은",

"color":"색","red":"빨간","blue":"파란","green":"초록의","yellow":"노란",
"black":"검은","brown":"갈색의","gray":"회색의",

"door":"문","window":"창문","wall":"벽","floor":"바닥, 층","roof":"지붕",
"table":"탁자","chair":"의자","bed":"침대","desk":"책상","clock":"시계",
"key":"열쇠","box":"상자","bag":"가방","book":"책","pen":"펜","pencil":"연필",

"game":"놀이, 경기","sport":"운동","team":"팀","player":"선수","win":"이기다",
"score":"점수","practice":"연습하다","exercise":"운동, 연습",

"music":"음악","song":"노래","sing":"노래하다","dance":"춤추다","movie":"영화",
"picture":"그림, 사진","photo":"사진","paint":"칠하다, 그리다",
"story":"이야기","news":"소식","letter":"편지, 글자","message":"전갈, 메시지",

"class":"수업, 반","lesson":"수업, 교훈","homework":"숙제","test":"시험",
"exam":"시험","grade":"성적, 학년","study":"공부하다","teach":"가르치다",
"question":"질문","subject":"과목, 주제","math":"수학","english":"영어",

"job":"일자리","office":"사무실","company":"회사","worker":"일하는 사람",
"doctor":"의사","nurse":"간호사","police":"경찰","farmer":"농부","cook":"요리하다","chef":"요리사",

"idea":"생각","dream":"꿈","hope":"바라다, 희망","fear":"두려움","anger":"화",
"joy":"기쁨","sad":"슬픈","glad":"기쁜","tired":"피곤한","busy":"바쁜","free":"자유로운",
"safe":"안전한","careful":"조심스러운","quiet":"조용한","loud":"시끄러운",
"clean":"깨끗한, 치우다","dirty":"더러운","full":"가득한","empty":"빈",
"easy":"쉬운","hard":"어려운, 단단한","strong":"강한","weak":"약한",
"fast":"빠른","slow":"느린","heavy":"무거운","light":"가벼운; 빛",
"deep":"깊은","wide":"넓은","narrow":"좁은","thick":"두꺼운","thin":"얇은",
"round":"둥근","straight":"곧은","sharp":"날카로운","smooth":"매끄러운",

"begin":"시작하다","finish":"끝내다","continue":"계속하다","change":"바꾸다",
"choose":"고르다","decide":"결정하다","forget":"잊다","remember":"기억하다",
"believe":"믿다","understand":"이해하다","explain":"설명하다","describe":"묘사하다",
"agree":"동의하다","refuse":"거절하다","promise":"약속하다","invite":"초대하다",
"visit":"방문하다","meet":"만나다","join":"함께하다","share":"나누다","bring":"가져오다",
"carry":"나르다","hold":"잡다, 열다","catch":"잡다","throw":"던지다","push":"밀다",
"pull":"당기다","break":"깨다","fix":"고치다","build":"짓다","grow":"자라다",
"kill":"죽이다","save":"구하다, 아끼다","lose":"잃다","search":"찾다","wait":"기다리다",
"follow":"따르다","lead":"이끌다","enter":"들어가다","arrive":"도착하다",
"return":"돌아오다","fall":"떨어지다","fly":"날다","swim":"헤엄치다","jump":"뛰다",
"stand":"서다","wear":"입다","wash":"씻다","draw":"그리다","send":"보내다",
"receive":"받다","borrow":"빌리다","lend":"빌려주다"
});

/* 지문에 자주 나오는 학술어 */
(function (extra) {
    var d = window.VOCAB_DICT;
    Object.keys(extra).forEach(function (k) { if (!d[k]) d[k] = extra[k]; });
})({
"as":"~로서, ~만큼","behavior":"행동","behaviour":"행동","behave":"행동하다",
"response":"반응, 대답","respond":"반응하다, 대답하다","gene":"유전자","genetic":"유전의",
"critic":"비평가","criticism":"비판, 비평","criticize":"비판하다","critical":"비판적인, 중요한",
"method":"방법","methodology":"방법론","sample":"표본, 견본","culture":"문화",
"estimate":"어림잡다, 추정","underestimate":"과소평가하다","overestimate":"과대평가하다",
"influential":"영향력 있는","publication":"출판, 발표","publish":"출판하다",
"investigation":"조사","investigate":"조사하다","origin":"기원","developmental":"발달의",
"personality":"성격","nurture":"양육하다, 기르다","emotional":"감정의","emotion":"감정",
"weakness":"약점","strength":"강점, 힘","firm":"단단한; 회사","measure":"재다, 조치",
"suggest":"제안하다, 시사하다","observe":"관찰하다","raise":"기르다, 올리다",
"lasting":"오래가는","contribute":"기여하다","contribution":"기여","factor":"요인",

"approach":"접근하다; 접근법","aspect":"측면","assume":"가정하다","assumption":"가정",
"available":"이용할 수 있는","benefit":"이익; 이롭다","capacity":"수용력, 능력",
"circumstance":"상황","complex":"복잡한","component":"구성 요소","concept":"개념",
"consequence":"결과","considerable":"상당한","consist":"이루어져 있다","constant":"끊임없는",
"constitute":"구성하다","context":"맥락","contrast":"대조","convention":"관습",
"crucial":"결정적인","define":"정의하다","definition":"정의","demonstrate":"보여 주다",
"derive":"끌어내다","distinct":"뚜렷이 다른","distinguish":"구별하다","domain":"영역",
"dominant":"우세한","element":"요소","emerge":"나타나다","enhance":"높이다",
"ensure":"보장하다","equivalent":"동등한","essential":"필수적인","establish":"세우다",
"estate":"재산, 부동산","ethical":"윤리적인","evaluate":"평가하다","exclude":"제외하다",
"exhibit":"보여 주다, 전시하다","exploit":"이용하다, 착취하다","external":"외부의",
"facilitate":"쉽게 하다","feature":"특징","framework":"틀","function":"기능; 작동하다",
"fundamental":"근본적인","generate":"만들어 내다","identical":"똑같은","identify":"알아보다",
"ignore":"무시하다","illustrate":"보여 주다, 예를 들다","implement":"실행하다",
"implication":"함의, 영향","imply":"암시하다","incentive":"동기, 유인","incorporate":"포함하다",
"indicate":"가리키다","individual":"개인; 개별의","inevitable":"피할 수 없는",
"infer":"추론하다","inherent":"타고난","initial":"처음의","initiate":"시작하다",
"innovation":"혁신","insight":"통찰","integrate":"통합하다","intense":"강렬한",
"interpret":"해석하다","interval":"간격","intervene":"개입하다","intrinsic":"본질적인",
"isolate":"고립시키다","justify":"정당화하다","maintain":"유지하다","manipulate":"조작하다",
"mechanism":"작동 원리","minimal":"최소의","modify":"수정하다","motive":"동기",
"mutual":"서로의","norm":"규범","notion":"개념","obtain":"얻다","occur":"일어나다",
"orient":"방향을 잡다","outcome":"결과","overlap":"겹치다",
"parallel":"평행한, 비슷한","participate":"참여하다","perceive":"인식하다",
"perspective":"관점","persist":"계속되다","phase":"단계","potential":"잠재적인; 가능성",
"precise":"정확한","predict":"예측하다","preliminary":"예비의","presume":"추정하다",
"previous":"이전의","primary":"주요한, 처음의","principal":"주요한; 교장",
"prior":"이전의","procedure":"절차","proceed":"진행하다","prohibit":"금지하다",
"promote":"촉진하다, 승진시키다","proportion":"비율","pursue":"추구하다",
"random":"무작위의","ratio":"비율","rational":"이성적인","reinforce":"강화하다",
"reject":"거부하다","relevant":"관련 있는","reluctant":"꺼리는","rely":"의지하다",
"restrict":"제한하다","retain":"유지하다","reveal":"드러내다","revise":"고치다",
"rigid":"뻣뻣한, 엄격한","scope":"범위","sequence":"차례, 연속","shift":"바뀌다; 변화",
"significant":"중요한, 상당한","similar":"비슷한","simulate":"흉내 내다","somewhat":"다소",
"specify":"명시하다","stable":"안정된","statistic":"통계","status":"지위, 상태",
"straightforward":"간단한, 솔직한","structure":"구조","subsequent":"뒤이은",
"substitute":"대신하다; 대체물","sufficient":"충분한","sustain":"지탱하다",
"tendency":"경향","theory":"이론","transform":"바꾸다","transmit":"전달하다",
"trigger":"불러일으키다; 방아쇠","ultimate":"궁극적인","undergo":"겪다",
"undertake":"떠맡다","uniform":"한결같은; 제복","utilize":"활용하다","valid":"타당한",
"vary":"다르다, 바꾸다","via":"~을 통해","virtual":"사실상의, 가상의","visible":"눈에 보이는",
"widespread":"널리 퍼진","yield":"내다, 양보하다"
});

/* 지문 시험에서 걸린 나머지 */
(function (extra) {
    var d = window.VOCAB_DICT;
    Object.keys(extra).forEach(function (k) { if (!d[k]) d[k] = extra[k]; });
})({
"temperature":"온도, 기온","glacier":"빙하","climb":"오르다","pledge":"약속하다; 서약",
"uneven":"고르지 않은","insufficient":"불충분한","sunrise":"해돋이","sunset":"해넘이",
"bicycle":"자전거","factory":"공장","fishing":"낚시","coastal":"해안의","coast":"해안",
"melt":"녹다","emission":"배출","carbon":"탄소","voluntary":"자발적인","binding":"구속력 있는",
"regulation":"규제","activist":"운동가","threaten":"위협하다","steadily":"꾸준히",
"flooding":"홍수","flood":"홍수","globe":"지구, 구","region":"지역","progress":"진전, 나아가다"
});

/* 파생 규칙에 잘못 걸리기 쉬운 낱말들 — 표제어로 못 박아 둔다 */
(function (extra) {
    var d = window.VOCAB_DICT;
    Object.keys(extra).forEach(function (k) { if (!d[k]) d[k] = extra[k]; });
})({
"several":"몇몇의, 여럿의","youth":"젊음, 젊은이","shoulder":"어깨","topic":"주제",
"offer":"제안하다; 제안","hardly":"거의 ~않다","nearly":"거의","listen":"듣다",
"passive":"수동적인","rubber":"고무","reply":"답하다; 대답","proper":"알맞은",
"panic":"공황; 당황하다","logic":"논리","famous":"유명한","various":"여러 가지의",
"nervous":"긴장한","curious":"궁금한","obvious":"뻔한, 명백한","jealous":"질투하는",
"precious":"귀중한","generous":"너그러운","numerous":"수많은","enormous":"거대한",
"delicious":"맛있는","religious":"종교의","ridiculous":"터무니없는","tremendous":"엄청난",
"dangerous":"위험한",

"general":"일반적인; 장군","natural":"자연의","central":"중심의","local":"지역의",
"moral":"도덕의","oral":"입의, 구두의","rural":"시골의","urban":"도시의",
"ideal":"이상적인","equal":"같은","usual":"보통의","formal":"격식 있는",
"normal":"보통의","legal":"법의, 합법의","loyal":"충성스러운","royal":"왕의",
"brutal":"잔인한","fatal":"치명적인","vital":"필수적인","global":"세계적인",
"social":"사회의","special":"특별한","personal":"개인의","physical":"신체의, 물리의",
"medical":"의학의","musical":"음악의","practical":"실용적인","political":"정치의",
"original":"본래의; 원본","digital":"디지털의","capital":"수도; 자본","festival":"축제",
"journal":"일지, 학술지","material":"재료; 물질의","mental":"정신의","similar":"비슷한",
"universal":"보편적인","financial":"재정의","industrial":"산업의","official":"공식의; 공무원",
"professional":"전문의","traditional":"전통의","additional":"추가의",
"international":"국제의","environmental":"환경의",

"north":"북쪽","south":"남쪽","east":"동쪽","west":"서쪽","truth":"진실",
"health":"건강","wealth":"부, 재산","depth":"깊이","width":"너비","length":"길이",
"birth":"탄생","death":"죽음","faith":"믿음","mouth":"입","path":"길",
"cloth":"천","breath":"숨","growth":"성장",

"active":"활동적인","native":"타고난; 원주민","relative":"친척; 상대적인",
"creative":"창의적인","positive":"긍정적인","negative":"부정적인","sensitive":"민감한",
"effective":"효과적인","expensive":"비싼","massive":"거대한",

"public":"대중의; 대중","basic":"기본의","classic":"고전의","comic":"웃긴; 만화",
"tragic":"비극의","toxic":"독성의","ethnic":"민족의","civic":"시민의",

"happen":"일어나다","sudden":"갑작스러운","wooden":"나무로 된","oxygen":"산소",
"citizen":"시민","dozen":"열두 개","token":"표, 징표",

"power":"힘","cover":"덮다; 표지","order":"명령, 순서; 주문하다","matter":"문제; 중요하다",
"master":"주인; 숙달하다","character":"성격, 등장인물","computer":"컴퓨터",
"consumer":"소비자","customer":"손님","manner":"방식, 태도","mirror":"거울",
"murder":"살인","partner":"동반자","quarter":"사분의 일","shelter":"쉼터",
"soldier":"군인","tower":"탑","wonder":"궁금해하다; 놀라움","whisper":"속삭이다",
"temper":"성질","tiger":"호랑이","thunder":"천둥","teenager":"십 대",
"transfer":"옮기다","chapter":"장, 챕터","prisoner":"죄수","prefer":"더 좋아하다",

"likely":"~할 것 같은","lonely":"외로운","lovely":"사랑스러운","friendly":"다정한",
"daily":"매일의","weekly":"주간의","monthly":"월간의","silly":"어리석은",
"supply":"공급하다","apply":"적용하다, 지원하다",

"duty":"의무","lady":"숙녀","lazy":"게으른","tiny":"아주 작은","unity":"통합",
"worry":"걱정하다","hurry":"서두르다","marry":"결혼하다","salary":"월급",
"safety":"안전","society":"사회","variety":"다양성","quality":"질","quantity":"양",
"energy":"에너지, 기운","enemy":"적","entry":"들어감, 참가","holiday":"휴일",
"injury":"부상","luxury":"사치","memory":"기억","mystery":"수수께끼","poetry":"시",
"poverty":"가난","privacy":"사생활","property":"재산, 속성","recovery":"회복",
"remedy":"치료법","secretary":"비서","therapy":"치료","treaty":"조약","victory":"승리"
});

/* ─────────────────────────────────────────────────────────────
   학생들이 채운 낱말.

   사전에 없는 낱말에 뜻을 적으면 한 표가 된다.
   같은 뜻을 적은 사람이 둘이 되면 여기로 올라와 모두가 쓴다.
   누가 적었는지는 남기지 않는다.

   붙박이 사전이 늘 이긴다. 빈자리만 메운다 —
   several 의 뜻을 누가 '심각한' 으로 덮어쓰는 일이 없어야 하기 때문이다.
   ───────────────────────────────────────────────────────────── */
window.VOCAB_SHARED = {};

window.vocabAddShared = function (map) {
    var d = window.VOCAB_DICT, prev = window.VOCAB_SHARED, n = 0;

    // 지난번에 얹었다가 이번에 빠진 낱말은 도로 뺀다 (학습부가 지웠을 때)
    Object.keys(prev).forEach(function (w) {
        if (!map || !map[w]) { if (d[w] === prev[w]) delete d[w]; }
    });

    window.VOCAB_SHARED = {};
    Object.keys(map || {}).forEach(function (k) {
        var w = String(k || "").toLowerCase();
        var m = map[k];
        if (!w || !w.match(/^[a-z]{2,40}$/)) return;
        if (typeof m !== "string" || !m || m.length > 200) return;
        window.VOCAB_SHARED[w] = m;
        // 빈자리면 채우고, 지난번에 우리가 얹었던 값이면 새 값으로 갈아 끼운다.
        // 붙박이 뜻은 어느 쪽도 아니므로 건드리지 않는다.
        if (!d[w] || d[w] === prev[w]) d[w] = m;
        if (d[w] === m) n++;
    });
    return n;
};

/* 뜻이 같은지 견주기 위한 꼴.
   띄어쓰기와 부호를 털어내, '뜻밖의 행운' 과 '뜻밖의행운' 을 같게 본다. */
window.vocabNormMeaning = function (t) {
    return String(t || "").toLowerCase()
        .replace(/[\s,.;:/~()\[\]{}'"!?\-]/g, "")
        .replace(/[\u00B7\u2014\u2013]/g, "")
        .slice(0, 60);
};
